// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: alora/auth/v1/token.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetTokenRequest names the product and, optionally, the scopes wanted.
type GetTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The product, as "product:<key>" (RFC 8707).
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Some of the scopes the client holds; none asks for all of them.
	Scopes        []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_alora_auth_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alora_auth_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_alora_auth_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// GetTokenResponse is an access token for one product.
type GetTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token: a JWT whose audience is "product:<key>".
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Always "Bearer".
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// The token's lifetime, in seconds.
	ExpiresIn int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// The scopes the token carries.
	Scopes        []string `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_alora_auth_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alora_auth_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_alora_auth_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *GetTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *GetTokenResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_alora_auth_v1_token_proto protoreflect.FileDescriptor

const file_alora_auth_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x19alora/auth/v1/token.proto\x12\ralora.auth.v1\"E\n" +
	"\x0fGetTokenRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\"\x8b\x01\n" +
	"\x10GetTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes2[\n" +
	"\fTokenService\x12K\n" +
	"\bGetToken\x12\x1e.alora.auth.v1.GetTokenRequest\x1a\x1f.alora.auth.v1.GetTokenResponseB>Z<github.com/prasath-23/Alora-Auth/alora-auth-go/authpb;authpbb\x06proto3"

var (
	file_alora_auth_v1_token_proto_rawDescOnce sync.Once
	file_alora_auth_v1_token_proto_rawDescData []byte
)

func file_alora_auth_v1_token_proto_rawDescGZIP() []byte {
	file_alora_auth_v1_token_proto_rawDescOnce.Do(func() {
		file_alora_auth_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alora_auth_v1_token_proto_rawDesc), len(file_alora_auth_v1_token_proto_rawDesc)))
	})
	return file_alora_auth_v1_token_proto_rawDescData
}

var file_alora_auth_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alora_auth_v1_token_proto_goTypes = []any{
	(*GetTokenRequest)(nil),  // 0: alora.auth.v1.GetTokenRequest
	(*GetTokenResponse)(nil), // 1: alora.auth.v1.GetTokenResponse
}
var file_alora_auth_v1_token_proto_depIdxs = []int32{
	0, // 0: alora.auth.v1.TokenService.GetToken:input_type -> alora.auth.v1.GetTokenRequest
	1, // 1: alora.auth.v1.TokenService.GetToken:output_type -> alora.auth.v1.GetTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alora_auth_v1_token_proto_init() }
func file_alora_auth_v1_token_proto_init() {
	if File_alora_auth_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alora_auth_v1_token_proto_rawDesc), len(file_alora_auth_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alora_auth_v1_token_proto_goTypes,
		DependencyIndexes: file_alora_auth_v1_token_proto_depIdxs,
		MessageInfos:      file_alora_auth_v1_token_proto_msgTypes,
	}.Build()
	File_alora_auth_v1_token_proto = out.File
	file_alora_auth_v1_token_proto_goTypes = nil
	file_alora_auth_v1_token_proto_depIdxs = nil
}
