// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec

CALL stp_InsertAuditLog(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type InsertAuditLogParams struct {
	ClientID      string
	ActorUserID   pgtype.Text
	EventType     string
	EventMetadata json.RawMessage
	IpAddress     pgtype.Text
	UserAgent     pgtype.Text
	RequestID     pgtype.Text
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: audit trail
//
// Insert only. There is deliberately no update or delete entry point, so the
// application has no way to rewrite history even if it tried.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ClientID,
		arg.ActorUserID,
		arg.EventType,
		arg.EventMetadata,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}
