// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clientNameById = `-- name: ClientNameById :one
SELECT name FROM (SELECT udf_ClientNameById($1) AS name) t WHERE name IS NOT NULL
`

// Filtered so an unknown tenant yields zero rows (see entitlements.sql).
func (q *Queries) ClientNameById(ctx context.Context, pClientid string) (string, error) {
	row := q.db.QueryRow(ctx, clientNameById, pClientid)
	var name string
	err := row.Scan(&name)
	return name, err
}

const createClient = `-- name: CreateClient :one
SELECT id, name, domain, domain_verified_at, allowed_idp_providers, require_mfa, subscription_status, max_seats, is_active, created_at, updated_at FROM stp_CreateClient(
    $1,
    $2,
    $3::"IdpProvider"[],
    $4,
    $5::"SubscriptionStatus",
    $6,
    $7
)
`

type CreateClientParams struct {
	Name                string
	Domain              pgtype.Text
	AllowedIdpProviders []IdpProvider
	RequireMfa          bool
	SubscriptionStatus  SubscriptionStatus
	MaxSeats            pgtype.Int4
	IsActive            bool
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (TblClient, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.Domain,
		arg.AllowedIdpProviders,
		arg.RequireMfa,
		arg.SubscriptionStatus,
		arg.MaxSeats,
		arg.IsActive,
	)
	var i TblClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.DomainVerifiedAt,
		&i.AllowedIdpProviders,
		&i.RequireMfa,
		&i.SubscriptionStatus,
		&i.MaxSeats,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
SELECT id, key, name, description, base_url, is_active, created_at, updated_at FROM stp_CreateProduct(
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateProductParams struct {
	Key         string
	Name        string
	Description pgtype.Text
	BaseUrl     pgtype.Text
	IsActive    bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (TblProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.IsActive,
	)
	var i TblProduct
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientById = `-- name: GetClientById :one

SELECT id, name, domain, domain_verified_at, allowed_idp_providers, require_mfa, subscription_status, max_seats, is_active, created_at, updated_at FROM udf_GetClientById($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: tenants and the product catalogue
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetClientById(ctx context.Context, pClientid string) (TblClient, error) {
	row := q.db.QueryRow(ctx, getClientById, pClientid)
	var i TblClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.DomainVerifiedAt,
		&i.AllowedIdpProviders,
		&i.RequireMfa,
		&i.SubscriptionStatus,
		&i.MaxSeats,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientOAuthGate = `-- name: GetClientOAuthGate :one
SELECT id, allowed_idp_providers, is_active FROM udf_GetClientOAuthGate($1)
`

func (q *Queries) GetClientOAuthGate(ctx context.Context, pClientid string) (VwClientoauthgate, error) {
	row := q.db.QueryRow(ctx, getClientOAuthGate, pClientid)
	var i VwClientoauthgate
	err := row.Scan(&i.ID, &i.AllowedIdpProviders, &i.IsActive)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, key, name, description, base_url, is_active, created_at, updated_at FROM udf_GetProductById($1, $2)
`

type GetProductByIdParams struct {
	PProductid  string
	PActiveonly bool
}

func (q *Queries) GetProductById(ctx context.Context, arg GetProductByIdParams) (TblProduct, error) {
	row := q.db.QueryRow(ctx, getProductById, arg.PProductid, arg.PActiveonly)
	var i TblProduct
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, key, name, description, base_url, is_active, created_at, updated_at FROM udf_ListActiveProducts()
`

func (q *Queries) ListActiveProducts(ctx context.Context) ([]TblProduct, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblProduct{}
	for rows.Next() {
		var i TblProduct
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productKeyById = `-- name: ProductKeyById :one
SELECT key FROM (SELECT udf_ProductKeyById($1) AS key) t WHERE key IS NOT NULL
`

// Filtered so an unknown product yields zero rows (see entitlements.sql).
func (q *Queries) ProductKeyById(ctx context.Context, pProductid string) (string, error) {
	row := q.db.QueryRow(ctx, productKeyById, pProductid)
	var key string
	err := row.Scan(&key)
	return key, err
}

const updateClient = `-- name: UpdateClient :one
SELECT id, name, domain, domain_verified_at, allowed_idp_providers, require_mfa, subscription_status, max_seats, is_active, created_at, updated_at FROM stp_UpdateClient(
    $1,
    $2,
    $3,
    $4::"IdpProvider"[],
    $5,
    $6::"SubscriptionStatus",
    $7,
    $8
)
`

type UpdateClientParams struct {
	ClientID            string
	Name                string
	RequireMfa          bool
	AllowedIdpProviders []IdpProvider
	DomainVerifiedAt    pgtype.Timestamptz
	SubscriptionStatus  SubscriptionStatus
	MaxSeats            pgtype.Int4
	IsActive            bool
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (TblClient, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ClientID,
		arg.Name,
		arg.RequireMfa,
		arg.AllowedIdpProviders,
		arg.DomainVerifiedAt,
		arg.SubscriptionStatus,
		arg.MaxSeats,
		arg.IsActive,
	)
	var i TblClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.DomainVerifiedAt,
		&i.AllowedIdpProviders,
		&i.RequireMfa,
		&i.SubscriptionStatus,
		&i.MaxSeats,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
SELECT id, key, name, description, base_url, is_active, created_at, updated_at FROM stp_UpdateProduct(
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type UpdateProductParams struct {
	ProductID   string
	Name        string
	Description pgtype.Text
	BaseUrl     pgtype.Text
	IsActive    bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (TblProduct, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.IsActive,
	)
	var i TblProduct
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
