// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeEMAIL     AccountType = "EMAIL"
	AccountTypeOAUTHONLY AccountType = "OAUTH_ONLY"
	AccountTypeHYBRID    AccountType = "HYBRID"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type IdpProvider string

const (
	IdpProviderEMAIL     IdpProvider = "EMAIL"
	IdpProviderGOOGLE    IdpProvider = "GOOGLE"
	IdpProviderMICROSOFT IdpProvider = "MICROSOFT"
	IdpProviderSAML      IdpProvider = "SAML"
	IdpProviderOIDC      IdpProvider = "OIDC"
)

func (e *IdpProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdpProvider(s)
	case string:
		*e = IdpProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for IdpProvider: %T", src)
	}
	return nil
}

type NullIdpProvider struct {
	IdpProvider IdpProvider
	Valid       bool // Valid is true if IdpProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdpProvider) Scan(value interface{}) error {
	if value == nil {
		ns.IdpProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdpProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdpProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdpProvider), nil
}

type InvitationStatus string

const (
	InvitationStatusPENDING  InvitationStatus = "PENDING"
	InvitationStatusACCEPTED InvitationStatus = "ACCEPTED"
	InvitationStatusEXPIRED  InvitationStatus = "EXPIRED"
	InvitationStatusREVOKED  InvitationStatus = "REVOKED"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus
	Valid            bool // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type SessionRevokedReason string

const (
	SessionRevokedReasonLOGOUT        SessionRevokedReason = "LOGOUT"
	SessionRevokedReasonLOGOUTALL     SessionRevokedReason = "LOGOUT_ALL"
	SessionRevokedReasonREUSEDETECTED SessionRevokedReason = "REUSE_DETECTED"
	SessionRevokedReasonADMIN         SessionRevokedReason = "ADMIN"
	SessionRevokedReasonEXPIRED       SessionRevokedReason = "EXPIRED"
)

func (e *SessionRevokedReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionRevokedReason(s)
	case string:
		*e = SessionRevokedReason(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionRevokedReason: %T", src)
	}
	return nil
}

type NullSessionRevokedReason struct {
	SessionRevokedReason SessionRevokedReason
	Valid                bool // Valid is true if SessionRevokedReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionRevokedReason) Scan(value interface{}) error {
	if value == nil {
		ns.SessionRevokedReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionRevokedReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionRevokedReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionRevokedReason), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusTRIAL     SubscriptionStatus = "TRIAL"
	SubscriptionStatusACTIVE    SubscriptionStatus = "ACTIVE"
	SubscriptionStatusSUSPENDED SubscriptionStatus = "SUSPENDED"
	SubscriptionStatusCANCELLED SubscriptionStatus = "CANCELLED"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type TblAuditLog struct {
	ID            string
	ClientID      string
	ActorUserID   pgtype.Text
	EventType     string
	EventMetadata json.RawMessage
	IpAddress     pgtype.Text
	UserAgent     pgtype.Text
	RequestID     pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type TblAuthorizationCode struct {
	ID                  string
	Code                string
	ProductID           string
	UserID              string
	RedirectUrl         string
	CodeChallenge       string
	CodeChallengeMethod string
	State               pgtype.Text
	ExpiresAt           pgtype.Timestamptz
	UsedAt              pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type TblClient struct {
	ID                  string
	Name                string
	Domain              pgtype.Text
	DomainVerifiedAt    pgtype.Timestamptz
	AllowedIdpProviders []IdpProvider
	RequireMfa          bool
	SubscriptionStatus  SubscriptionStatus
	MaxSeats            pgtype.Int4
	IsActive            bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type TblClientProduct struct {
	ID        string
	ClientID  string
	ProductID string
	IsActive  bool
	SeatLimit pgtype.Int4
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type TblGroup struct {
	ID          string
	ClientID    string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TblGroupFeature struct {
	ID         string
	GroupID    string
	FeatureKey string
}

type TblInvitation struct {
	ID               string
	Email            string
	ClientID         string
	InvitedByUserID  string
	TokenHash        string
	ExpiresAt        pgtype.Timestamptz
	Status           InvitationStatus
	AcceptedAt       pgtype.Timestamptz
	AcceptedByUserID pgtype.Text
	RevokedAt        pgtype.Timestamptz
	RevokedByUserID  pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TblInvitationProduct struct {
	ID           string
	InvitationID string
	ProductID    string
	RoleName     string
}

type TblLinkedIdentity struct {
	ID            string
	UserID        string
	Provider      IdpProvider
	ProviderID    string
	EmailVerified bool
	CreatedAt     pgtype.Timestamptz
}

type TblPasswordResetToken struct {
	ID        string
	UserID    string
	ClientID  string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedBy string
	CreatedAt pgtype.Timestamptz
}

type TblProduct struct {
	ID          string
	Key         string
	Name        string
	Description pgtype.Text
	BaseUrl     pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TblProductPermission struct {
	ID         string
	UserID     string
	ClientID   string
	ProductID  string
	RoleName   string
	GrantedBy  pgtype.Text
	ValidFrom  pgtype.Timestamptz
	ValidUntil pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type TblSchemaMigration struct {
	Version    string
	Checksum   string
	AppliedAt  pgtype.Timestamptz
	AppliedBy  string
	DurationMs pgtype.Int4
}

type TblUser struct {
	ID                 string
	ClientID           string
	Email              string
	PasswordHash       pgtype.Text
	AccountType        AccountType
	IsActive           bool
	IsGlobalAdmin      bool
	PermissionsVersion int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type TblUserGroup struct {
	UserID     string
	GroupID    string
	ClientID   string
	AssignedAt pgtype.Timestamptz
	AssignedBy pgtype.Text
}

type TblUserSession struct {
	ID               string
	UserID           string
	ClientID         string
	SessionUuid      string
	FamilyID         string
	Generation       int32
	RefreshTokenHash string
	PrevTokenHash    pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevokedReason    NullSessionRevokedReason
	IpAddress        pgtype.Text
	DeviceLabel      pgtype.Text
	UserAgent        pgtype.Text
	LastSeenAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	ReplacedByID     pgtype.Text
}

type VwClientoauthgate struct {
	ID                  string
	AllowedIdpProviders []IdpProvider
	IsActive            bool
}

type VwClientproductdetail struct {
	ID                 string
	ClientID           string
	ProductID          string
	IsActive           bool
	SeatLimit          pgtype.Int4
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	ProductKey         string
	ProductName        string
	ProductDescription pgtype.Text
	ProductBaseUrl     pgtype.Text
	ProductIsActive    bool
}

type VwGroupdetailrow struct {
	ID          string
	ClientID    string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	Features    interface{}
	UserID      pgtype.Text
	UserEmail   pgtype.Text
	AssignedAt  pgtype.Timestamptz
}

type VwGrouplistitem struct {
	ID          string
	ClientID    string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Features    interface{}
	MemberCount int64
}

type VwInvitationlistitem struct {
	ID        string
	ClientID  string
	Email     string
	Status    InvitationStatus
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type VwInvitationproductrole struct {
	InvitationID string
	ProductID    string
	ProductKey   string
	ProductName  string
	RoleName     string
}

type VwLinkedidentityowner struct {
	Provider   IdpProvider
	ProviderID string
	UserID     string
	ClientID   string
	IsActive   bool
}

type VwPendinginvitation struct {
	ID                  string
	Email               string
	ClientID            string
	InvitedByUserID     string
	TokenHash           string
	ExpiresAt           pgtype.Timestamptz
	AllowedIdpProviders []IdpProvider
	ClientName          string
}

type VwSessionowner struct {
	ID               string
	UserID           string
	ClientID         string
	RevokedAt        pgtype.Timestamptz
	RefreshTokenHash string
}

type VwSessionsummary struct {
	ID          string
	ClientID    string
	DeviceLabel pgtype.Text
	IpAddress   pgtype.Text
	LastSeenAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type VwUsercredential struct {
	ID                 string
	ClientID           string
	Email              string
	PasswordHash       pgtype.Text
	AccountType        AccountType
	IsGlobalAdmin      bool
	PermissionsVersion int32
}

type VwUserfreshness struct {
	ID                 string
	PermissionsVersion int32
	IsActive           bool
	DeletedAt          pgtype.Timestamptz
}

type VwUsergroupmembership struct {
	UserID     string
	ClientID   string
	GroupID    string
	GroupName  string
	AssignedAt pgtype.Timestamptz
}

type VwUseridentity struct {
	ID                 string
	ClientID           string
	Email              string
	IsGlobalAdmin      bool
	PermissionsVersion int32
}

type VwUserlistitem struct {
	ID                 string
	ClientID           string
	Email              string
	AccountType        AccountType
	IsActive           bool
	IsGlobalAdmin      bool
	PermissionsVersion int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type VwUserproductrole struct {
	UserID      string
	ClientID    string
	ProductID   string
	ProductKey  string
	ProductName string
	RoleName    string
	ValidUntil  pgtype.Timestamptz
}

type VwUsertenantscoped struct {
	ID                 string
	ClientID           string
	Email              string
	AccountType        AccountType
	IsActive           bool
	IsGlobalAdmin      bool
	PermissionsVersion int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type VwValidresettoken struct {
	ID        string
	UserID    string
	ClientID  string
	TokenHash string
	Email     string
	IsActive  bool
	DeletedAt pgtype.Timestamptz
}
