// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAuthorizationCode = `-- name: ClaimAuthorizationCode :one
SELECT id, code, product_id, user_id, redirect_url, code_challenge, code_challenge_method, state, expires_at, used_at, created_at FROM stp_ClaimAuthorizationCode($1)
`

func (q *Queries) ClaimAuthorizationCode(ctx context.Context, pCode string) (TblAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, claimAuthorizationCode, pCode)
	var i TblAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.UserID,
		&i.RedirectUrl,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.State,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cleanupExpiredAuthCodes = `-- name: CleanupExpiredAuthCodes :one
SELECT stp_CleanupExpiredAuthCodes()
`

func (q *Queries) CleanupExpiredAuthCodes(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, cleanupExpiredAuthCodes)
	var stp_cleanupexpiredauthcodes int32
	err := row.Scan(&stp_cleanupexpiredauthcodes)
	return stp_cleanupexpiredauthcodes, err
}

const clientIdByVerifiedDomain = `-- name: ClientIdByVerifiedDomain :one
SELECT id FROM (SELECT udf_ClientIdByVerifiedDomain($1) AS id) t WHERE id IS NOT NULL
`

// Filtered so an unknown domain yields zero rows (see entitlements.sql).
func (q *Queries) ClientIdByVerifiedDomain(ctx context.Context, pDomain string) (string, error) {
	row := q.db.QueryRow(ctx, clientIdByVerifiedDomain, pDomain)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one

SELECT id, code, product_id, user_id, redirect_url, code_challenge, code_challenge_method, state, expires_at, used_at, created_at FROM stp_CreateAuthorizationCode(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreateAuthorizationCodeParams struct {
	Code                string
	ProductID           string
	UserID              string
	RedirectUrl         string
	CodeChallenge       string
	CodeChallengeMethod string
	State               pgtype.Text
	ExpiresAt           pgtype.Timestamptz
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: OAuth2 authorization codes and federated identities
//
// The single-use guarantee is enforced inside stp_ClaimAuthorizationCode as one
// atomic UPDATE, so no caller can reintroduce a check-then-act race.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (TblAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.Code,
		arg.ProductID,
		arg.UserID,
		arg.RedirectUrl,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.State,
		arg.ExpiresAt,
	)
	var i TblAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.UserID,
		&i.RedirectUrl,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.State,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLinkedIdentity = `-- name: CreateLinkedIdentity :one
SELECT id, user_id, provider, provider_id, email_verified, created_at FROM stp_CreateLinkedIdentity(
    $1,
    $2::"IdpProvider",
    $3,
    $4
)
`

type CreateLinkedIdentityParams struct {
	UserID        string
	Provider      IdpProvider
	ProviderID    string
	EmailVerified bool
}

func (q *Queries) CreateLinkedIdentity(ctx context.Context, arg CreateLinkedIdentityParams) (TblLinkedIdentity, error) {
	row := q.db.QueryRow(ctx, createLinkedIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.EmailVerified,
	)
	var i TblLinkedIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkedIdentity = `-- name: GetLinkedIdentity :one
SELECT provider, provider_id, user_id, client_id, is_active FROM udf_GetLinkedIdentity(
    $1::"IdpProvider",
    $2
)
`

type GetLinkedIdentityParams struct {
	Provider   IdpProvider
	ProviderID string
}

func (q *Queries) GetLinkedIdentity(ctx context.Context, arg GetLinkedIdentityParams) (VwLinkedidentityowner, error) {
	row := q.db.QueryRow(ctx, getLinkedIdentity, arg.Provider, arg.ProviderID)
	var i VwLinkedidentityowner
	err := row.Scan(
		&i.Provider,
		&i.ProviderID,
		&i.UserID,
		&i.ClientID,
		&i.IsActive,
	)
	return i, err
}
