// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passwordreset.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResetToken = `-- name: CreateResetToken :one
SELECT id, user_id, client_id, token_hash, expires_at, used_at, created_by, created_at FROM stp_CreateResetToken($1, $2, $3, $4, $5)
`

type CreateResetTokenParams struct {
	PUserid    string
	PClientid  string
	PTokenhash string
	PExpiresat pgtype.Timestamptz
	PCreatedby string
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (TblPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createResetToken,
		arg.PUserid,
		arg.PClientid,
		arg.PTokenhash,
		arg.PExpiresat,
		arg.PCreatedby,
	)
	var i TblPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUnusedResetTokens = `-- name: DeleteUnusedResetTokens :exec
CALL stp_DeleteUnusedResetTokens($1)
`

func (q *Queries) DeleteUnusedResetTokens(ctx context.Context, pUserid string) error {
	_, err := q.db.Exec(ctx, deleteUnusedResetTokens, pUserid)
	return err
}

const getValidResetToken = `-- name: GetValidResetToken :one

SELECT id, user_id, client_id, token_hash, email, is_active, deleted_at FROM udf_GetValidResetToken($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: password reset
//
// vw_ValidResetToken carries the unused and unexpired predicates and surfaces the
// owner's state, so the caller cannot honour a spent link or revive a disabled
// account.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetValidResetToken(ctx context.Context, pTokenhash string) (VwValidresettoken, error) {
	row := q.db.QueryRow(ctx, getValidResetToken, pTokenhash)
	var i VwValidresettoken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.Email,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const markResetTokenUsed = `-- name: MarkResetTokenUsed :exec
CALL stp_MarkResetTokenUsed($1)
`

func (q *Queries) MarkResetTokenUsed(ctx context.Context, pTokenid string) error {
	_, err := q.db.Exec(ctx, markResetTokenUsed, pTokenid)
	return err
}
