// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveEmailExists(ctx context.Context, arg ActiveEmailExistsParams) (bool, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: subscriptions and product-role grants
	// ─────────────────────────────────────────────────────────────────────────────
	// Filtered so a NULL (no subscription) yields ZERO ROWS rather than one NULL
	// row: a scalar function always returns a row, and the caller distinguishes
	// "not found" by pgx.ErrNoRows.
	ActiveSubscriptionId(ctx context.Context, arg ActiveSubscriptionIdParams) (string, error)
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	BumpPermissionsVersion(ctx context.Context, arg BumpPermissionsVersionParams) error
	ClaimAuthorizationCode(ctx context.Context, pCode string) (TblAuthorizationCode, error)
	ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (TblInvitation, error)
	CleanupExpiredAuthCodes(ctx context.Context) (int32, error)
	// Filtered so an unknown domain yields zero rows (see entitlements.sql).
	ClientIdByVerifiedDomain(ctx context.Context, pDomain string) (string, error)
	// Filtered so an unknown tenant yields zero rows (see entitlements.sql).
	ClientNameById(ctx context.Context, pClientid string) (string, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: OAuth2 authorization codes and federated identities
	//
	// The single-use guarantee is enforced inside stp_ClaimAuthorizationCode as one
	// atomic UPDATE, so no caller can reintroduce a check-then-act race.
	// ─────────────────────────────────────────────────────────────────────────────
	CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (TblAuthorizationCode, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (TblClient, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (TblGroup, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TblInvitation, error)
	CreateInvitationProduct(ctx context.Context, arg CreateInvitationProductParams) error
	CreateLinkedIdentity(ctx context.Context, arg CreateLinkedIdentityParams) (TblLinkedIdentity, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (TblProduct, error)
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (TblPasswordResetToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (TblUserSession, error)
	CreateSuccessorSession(ctx context.Context, arg CreateSuccessorSessionParams) (TblUserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (TblUser, error)
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int32, error)
	DeleteProductPermission(ctx context.Context, arg DeleteProductPermissionParams) (int32, error)
	DeleteUnusedResetTokens(ctx context.Context, pUserid string) error
	ExpireInvitations(ctx context.Context, pBatchsize int32) error
	ExpireSessions(ctx context.Context, pBatchsize int32) error
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: tenants and the product catalogue
	// ─────────────────────────────────────────────────────────────────────────────
	GetClientById(ctx context.Context, pClientid string) (TblClient, error)
	GetClientOAuthGate(ctx context.Context, pClientid string) (VwClientoauthgate, error)
	GetClientSessionById(ctx context.Context, arg GetClientSessionByIdParams) (VwSessionowner, error)
	GetGraceSuccessor(ctx context.Context, arg GetGraceSuccessorParams) (TblUserSession, error)
	GetGroupDetail(ctx context.Context, arg GetGroupDetailParams) ([]VwGroupdetailrow, error)
	GetGroupTenantScoped(ctx context.Context, arg GetGroupTenantScopedParams) (TblGroup, error)
	GetLinkedIdentity(ctx context.Context, arg GetLinkedIdentityParams) (VwLinkedidentityowner, error)
	GetOAuthLinkableUser(ctx context.Context, arg GetOAuthLinkableUserParams) (VwUsertenantscoped, error)
	GetPendingInvitation(ctx context.Context, pTokenhash string) (VwPendinginvitation, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: invitations
	//
	// The redeemable-invitation predicates (pending, unexpired, active tenant) live
	// in vw_PendingInvitation, so every lookup below inherits them and no caller can
	// accidentally honour a dead invitation.
	// ─────────────────────────────────────────────────────────────────────────────
	GetPendingInviteByEmail(ctx context.Context, arg GetPendingInviteByEmailParams) (VwPendinginvitation, error)
	GetProductById(ctx context.Context, arg GetProductByIdParams) (TblProduct, error)
	GetProductPermission(ctx context.Context, arg GetProductPermissionParams) (VwUserproductrole, error)
	GetSessionById(ctx context.Context, pSessionid string) (TblUserSession, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: sessions (refresh-token rotation)
	//
	// The rotation sequence is orchestrated by the API inside ONE transaction, but
	// every individual statement is a database object. In particular the lock is
	// taken by udf_GetSessionByRefreshHashForUpdate, so the FOR UPDATE that
	// serialises concurrent rotations lives in the database, not in application SQL.
	// ─────────────────────────────────────────────────────────────────────────────
	GetSessionByRefreshHashForUpdate(ctx context.Context, pTokenhash string) (TblUserSession, error)
	GetSessionForLogout(ctx context.Context, pTokenhash string) (VwSessionowner, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: users
	//
	// Every statement in this folder is a CALL of a procedure or a SELECT from a
	// function. Nothing here reads or writes a table directly, so all query logic —
	// predicates, projections, tenant scoping — lives in the database objects under
	// db/Tables, db/Views and db/Programmability and can be reviewed there in one
	// place.
	// ─────────────────────────────────────────────────────────────────────────────
	GetUserById(ctx context.Context, pUserid string) (TblUser, error)
	GetUserCredentialByEmail(ctx context.Context, pEmail string) (VwUsercredential, error)
	GetUserFreshness(ctx context.Context, pUserid string) (VwUserfreshness, error)
	GetUserIdentityForToken(ctx context.Context, pUserid string) (VwUseridentity, error)
	GetUserTenantScoped(ctx context.Context, arg GetUserTenantScopedParams) (VwUsertenantscoped, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: password reset
	//
	// vw_ValidResetToken carries the unused and unexpired predicates and surfaces the
	// owner's state, so the caller cannot honour a spent link or revive a disabled
	// account.
	// ─────────────────────────────────────────────────────────────────────────────
	GetValidResetToken(ctx context.Context, pTokenhash string) (VwValidresettoken, error)
	HasGroupFeature(ctx context.Context, arg HasGroupFeatureParams) (bool, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: readiness probe
	// ─────────────────────────────────────────────────────────────────────────────
	HealthCheck(ctx context.Context) (int32, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: audit trail
	//
	// Insert only. There is deliberately no update or delete entry point, so the
	// application has no way to rewrite history even if it tried.
	// ─────────────────────────────────────────────────────────────────────────────
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	ListActiveProducts(ctx context.Context) ([]TblProduct, error)
	ListActiveSessions(ctx context.Context, pClientid string) ([]VwSessionsummary, error)
	ListClientProducts(ctx context.Context, pClientid string) ([]VwClientproductdetail, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: groups and feature grants
	//
	// Tenant ownership for the feature write is enforced inside
	// stp_SetGroupFeatures, which re-derives it through tbl_groups. The API cannot
	// bypass it by passing a foreign group id.
	// ─────────────────────────────────────────────────────────────────────────────
	ListGroups(ctx context.Context, pClientid string) ([]VwGrouplistitem, error)
	ListInvitationProducts(ctx context.Context, pInvitationid string) ([]VwInvitationproductrole, error)
	ListInvitations(ctx context.Context, pClientid string) ([]VwInvitationlistitem, error)
	ListUserFeatures(ctx context.Context, arg ListUserFeaturesParams) ([]pgtype.Text, error)
	ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]VwUsergroupmembership, error)
	ListUserProductRoles(ctx context.Context, arg ListUserProductRolesParams) ([]VwUserproductrole, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]VwUserlistitem, error)
	MarkResetTokenUsed(ctx context.Context, pTokenid string) error
	MarkSessionReplaced(ctx context.Context, arg MarkSessionReplacedParams) error
	// Filtered so an unknown product yields zero rows (see entitlements.sql).
	ProductKeyById(ctx context.Context, pProductid string) (string, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int32, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int32, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int32, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int32, error)
	RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error
	SetGroupFeatures(ctx context.Context, arg SetGroupFeaturesParams) (int32, error)
	SetInvitationAcceptedBy(ctx context.Context, arg SetInvitationAcceptedByParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (int32, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) (TblClient, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (TblGroup, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (TblProduct, error)
	UpsertProductPermission(ctx context.Context, arg UpsertProductPermissionParams) error
	// Filtered so an unresolvable cursor yields zero rows (see entitlements.sql).
	UserCursorPosition(ctx context.Context, arg UserCursorPositionParams) (pgtype.Timestamptz, error)
	// Filtered so an unknown address yields zero rows (see entitlements.sql).
	UserIdByEmail(ctx context.Context, arg UserIdByEmailParams) (string, error)
}

var _ Querier = (*Queries)(nil)
