// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
CALL stp_AddGroupMember(
    $1,
    $2,
    $3,
    $4
)
`

type AddGroupMemberParams struct {
	UserID     string
	GroupID    string
	ClientID   string
	AssignedBy pgtype.Text
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.ClientID,
		arg.AssignedBy,
	)
	return err
}

const createGroup = `-- name: CreateGroup :one
SELECT id, client_id, name, description, created_at, updated_at FROM stp_CreateGroup(
    $1,
    $2,
    $3
)
`

type CreateGroupParams struct {
	ClientID    string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (TblGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.ClientID, arg.Name, arg.Description)
	var i TblGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :one
SELECT stp_DeleteGroup($1, $2)
`

type DeleteGroupParams struct {
	PGroupid  string
	PClientid string
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteGroup, arg.PGroupid, arg.PClientid)
	var stp_deletegroup int32
	err := row.Scan(&stp_deletegroup)
	return stp_deletegroup, err
}

const getGroupDetail = `-- name: GetGroupDetail :many
SELECT id, client_id, name, description, created_at, features, user_id, user_email, assigned_at FROM udf_GetGroupDetail($1, $2)
`

type GetGroupDetailParams struct {
	PGroupid  string
	PClientid string
}

func (q *Queries) GetGroupDetail(ctx context.Context, arg GetGroupDetailParams) ([]VwGroupdetailrow, error) {
	rows, err := q.db.Query(ctx, getGroupDetail, arg.PGroupid, arg.PClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwGroupdetailrow{}
	for rows.Next() {
		var i VwGroupdetailrow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Features,
			&i.UserID,
			&i.UserEmail,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupTenantScoped = `-- name: GetGroupTenantScoped :one
SELECT id, client_id, name, description, created_at, updated_at FROM udf_GetGroupTenantScoped($1, $2)
`

type GetGroupTenantScopedParams struct {
	PGroupid  string
	PClientid string
}

func (q *Queries) GetGroupTenantScoped(ctx context.Context, arg GetGroupTenantScopedParams) (TblGroup, error) {
	row := q.db.QueryRow(ctx, getGroupTenantScoped, arg.PGroupid, arg.PClientid)
	var i TblGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasGroupFeature = `-- name: HasGroupFeature :one
SELECT udf_HasGroupFeature($1, $2, $3)
`

type HasGroupFeatureParams struct {
	PFeaturekey string
	PClientid   string
	PUserid     string
}

func (q *Queries) HasGroupFeature(ctx context.Context, arg HasGroupFeatureParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasGroupFeature, arg.PFeaturekey, arg.PClientid, arg.PUserid)
	var udf_hasgroupfeature bool
	err := row.Scan(&udf_hasgroupfeature)
	return udf_hasgroupfeature, err
}

const listGroups = `-- name: ListGroups :many

SELECT id, client_id, name, description, created_at, updated_at, features, member_count FROM udf_ListGroups($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: groups and feature grants
//
// Tenant ownership for the feature write is enforced inside
// stp_SetGroupFeatures, which re-derives it through tbl_groups. The API cannot
// bypass it by passing a foreign group id.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) ListGroups(ctx context.Context, pClientid string) ([]VwGrouplistitem, error) {
	rows, err := q.db.Query(ctx, listGroups, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwGrouplistitem{}
	for rows.Next() {
		var i VwGrouplistitem
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Features,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :one
SELECT stp_RemoveGroupMember($1, $2, $3)
`

type RemoveGroupMemberParams struct {
	PUserid   string
	PGroupid  string
	PClientid string
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int32, error) {
	row := q.db.QueryRow(ctx, removeGroupMember, arg.PUserid, arg.PGroupid, arg.PClientid)
	var stp_removegroupmember int32
	err := row.Scan(&stp_removegroupmember)
	return stp_removegroupmember, err
}

const setGroupFeatures = `-- name: SetGroupFeatures :one
SELECT stp_SetGroupFeatures(
    $1,
    $2,
    $3::text[]
)
`

type SetGroupFeaturesParams struct {
	GroupID     string
	ClientID    string
	FeatureKeys []string
}

func (q *Queries) SetGroupFeatures(ctx context.Context, arg SetGroupFeaturesParams) (int32, error) {
	row := q.db.QueryRow(ctx, setGroupFeatures, arg.GroupID, arg.ClientID, arg.FeatureKeys)
	var stp_setgroupfeatures int32
	err := row.Scan(&stp_setgroupfeatures)
	return stp_setgroupfeatures, err
}

const updateGroup = `-- name: UpdateGroup :one
SELECT id, client_id, name, description, created_at, updated_at FROM stp_UpdateGroup(
    $1,
    $2,
    $3,
    $4
)
`

type UpdateGroupParams struct {
	GroupID     string
	ClientID    string
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (TblGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.GroupID,
		arg.ClientID,
		arg.Name,
		arg.Description,
	)
	var i TblGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
