// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM stp_CreateSession(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateSessionParams struct {
	UserID           string
	ClientID         string
	SessionUuid      string
	FamilyID         string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	IpAddress        pgtype.Text
	DeviceLabel      pgtype.Text
	UserAgent        pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.ClientID,
		arg.SessionUuid,
		arg.FamilyID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.DeviceLabel,
		arg.UserAgent,
	)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const createSuccessorSession = `-- name: CreateSuccessorSession :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM stp_CreateSuccessorSession(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateSuccessorSessionParams struct {
	UserID           string
	ClientID         string
	SessionUuid      string
	FamilyID         string
	Generation       int32
	RefreshTokenHash string
	PrevTokenHash    pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	IpAddress        pgtype.Text
	DeviceLabel      pgtype.Text
	UserAgent        pgtype.Text
}

func (q *Queries) CreateSuccessorSession(ctx context.Context, arg CreateSuccessorSessionParams) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, createSuccessorSession,
		arg.UserID,
		arg.ClientID,
		arg.SessionUuid,
		arg.FamilyID,
		arg.Generation,
		arg.RefreshTokenHash,
		arg.PrevTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.DeviceLabel,
		arg.UserAgent,
	)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const expireSessions = `-- name: ExpireSessions :exec
CALL stp_ExpireSessions($1)
`

func (q *Queries) ExpireSessions(ctx context.Context, pBatchsize int32) error {
	_, err := q.db.Exec(ctx, expireSessions, pBatchsize)
	return err
}

const getClientSessionById = `-- name: GetClientSessionById :one
SELECT id, user_id, client_id, revoked_at, refresh_token_hash FROM udf_GetClientSessionById($1, $2)
`

type GetClientSessionByIdParams struct {
	PSessionid string
	PClientid  string
}

func (q *Queries) GetClientSessionById(ctx context.Context, arg GetClientSessionByIdParams) (VwSessionowner, error) {
	row := q.db.QueryRow(ctx, getClientSessionById, arg.PSessionid, arg.PClientid)
	var i VwSessionowner
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.RevokedAt,
		&i.RefreshTokenHash,
	)
	return i, err
}

const getGraceSuccessor = `-- name: GetGraceSuccessor :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM udf_GetGraceSuccessor($1, $2)
`

type GetGraceSuccessorParams struct {
	PPrevtokenhash string
	PCreatedafter  pgtype.Timestamptz
}

func (q *Queries) GetGraceSuccessor(ctx context.Context, arg GetGraceSuccessorParams) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, getGraceSuccessor, arg.PPrevtokenhash, arg.PCreatedafter)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM udf_GetSessionById($1)
`

func (q *Queries) GetSessionById(ctx context.Context, pSessionid string) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, getSessionById, pSessionid)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getSessionByRefreshHashForUpdate = `-- name: GetSessionByRefreshHashForUpdate :one

SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM udf_GetSessionByRefreshHashForUpdate($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: sessions (refresh-token rotation)
//
// The rotation sequence is orchestrated by the API inside ONE transaction, but
// every individual statement is a database object. In particular the lock is
// taken by udf_GetSessionByRefreshHashForUpdate, so the FOR UPDATE that
// serialises concurrent rotations lives in the database, not in application SQL.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetSessionByRefreshHashForUpdate(ctx context.Context, pTokenhash string) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHashForUpdate, pTokenhash)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getSessionForLogout = `-- name: GetSessionForLogout :one
SELECT id, user_id, client_id, revoked_at, refresh_token_hash FROM udf_GetSessionForLogout($1)
`

func (q *Queries) GetSessionForLogout(ctx context.Context, pTokenhash string) (VwSessionowner, error) {
	row := q.db.QueryRow(ctx, getSessionForLogout, pTokenhash)
	var i VwSessionowner
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.RevokedAt,
		&i.RefreshTokenHash,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, client_id, device_label, ip_address, last_seen_at, created_at FROM udf_ListActiveSessions($1)
`

func (q *Queries) ListActiveSessions(ctx context.Context, pClientid string) ([]VwSessionsummary, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwSessionsummary{}
	for rows.Next() {
		var i VwSessionsummary
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DeviceLabel,
			&i.IpAddress,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionReplaced = `-- name: MarkSessionReplaced :exec
CALL stp_MarkSessionReplaced($1, $2)
`

type MarkSessionReplacedParams struct {
	PSessionid    string
	PReplacedbyid string
}

func (q *Queries) MarkSessionReplaced(ctx context.Context, arg MarkSessionReplacedParams) error {
	_, err := q.db.Exec(ctx, markSessionReplaced, arg.PSessionid, arg.PReplacedbyid)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :one
SELECT stp_RevokeAllUserSessions(
    $1,
    $2::"SessionRevokedReason"
)
`

type RevokeAllUserSessionsParams struct {
	UserID string
	Reason SessionRevokedReason
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeAllUserSessions, arg.UserID, arg.Reason)
	var stp_revokeallusersessions int32
	err := row.Scan(&stp_revokeallusersessions)
	return stp_revokeallusersessions, err
}

const revokeSession = `-- name: RevokeSession :one
SELECT stp_RevokeSession(
    $1,
    $2,
    $3::"SessionRevokedReason"
)
`

type RevokeSessionParams struct {
	SessionID string
	ClientID  string
	Reason    SessionRevokedReason
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.SessionID, arg.ClientID, arg.Reason)
	var stp_revokesession int32
	err := row.Scan(&stp_revokesession)
	return stp_revokesession, err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
CALL stp_RevokeTokenFamily($1, $2)
`

type RevokeTokenFamilyParams struct {
	PFamilyid string
	PReason   string
}

func (q *Queries) RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, arg.PFamilyid, arg.PReason)
	return err
}
