// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeEmailExists = `-- name: ActiveEmailExists :one
SELECT udf_ActiveEmailExists($1, $2)
`

type ActiveEmailExistsParams struct {
	PClientid string
	PEmail    string
}

func (q *Queries) ActiveEmailExists(ctx context.Context, arg ActiveEmailExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, activeEmailExists, arg.PClientid, arg.PEmail)
	var udf_activeemailexists bool
	err := row.Scan(&udf_activeemailexists)
	return udf_activeemailexists, err
}

const bumpPermissionsVersion = `-- name: BumpPermissionsVersion :exec
CALL stp_BumpPermissionsVersion($1, $2)
`

type BumpPermissionsVersionParams struct {
	PUserid   string
	PClientid string
}

func (q *Queries) BumpPermissionsVersion(ctx context.Context, arg BumpPermissionsVersionParams) error {
	_, err := q.db.Exec(ctx, bumpPermissionsVersion, arg.PUserid, arg.PClientid)
	return err
}

const createUser = `-- name: CreateUser :one
SELECT id, client_id, email, password_hash, account_type, is_active, is_global_admin, permissions_version, created_at, updated_at, deleted_at FROM stp_CreateUser(
    $1,
    $2,
    $3,
    $4::"AccountType"
)
`

type CreateUserParams struct {
	ClientID     string
	Email        string
	PasswordHash pgtype.Text
	AccountType  AccountType
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (TblUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClientID,
		arg.Email,
		arg.PasswordHash,
		arg.AccountType,
	)
	var i TblUser
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.AccountType,
		&i.IsActive,
		&i.IsGlobalAdmin,
		&i.PermissionsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOAuthLinkableUser = `-- name: GetOAuthLinkableUser :one
SELECT id, client_id, email, account_type, is_active, is_global_admin, permissions_version, created_at, updated_at FROM udf_GetOAuthLinkableUser($1, $2)
`

type GetOAuthLinkableUserParams struct {
	PClientid string
	PEmail    string
}

func (q *Queries) GetOAuthLinkableUser(ctx context.Context, arg GetOAuthLinkableUserParams) (VwUsertenantscoped, error) {
	row := q.db.QueryRow(ctx, getOAuthLinkableUser, arg.PClientid, arg.PEmail)
	var i VwUsertenantscoped
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.AccountType,
		&i.IsActive,
		&i.IsGlobalAdmin,
		&i.PermissionsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one

SELECT id, client_id, email, password_hash, account_type, is_active, is_global_admin, permissions_version, created_at, updated_at, deleted_at FROM udf_GetUserById($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: users
//
// Every statement in this folder is a CALL of a procedure or a SELECT from a
// function. Nothing here reads or writes a table directly, so all query logic —
// predicates, projections, tenant scoping — lives in the database objects under
// db/Tables, db/Views and db/Programmability and can be reviewed there in one
// place.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetUserById(ctx context.Context, pUserid string) (TblUser, error) {
	row := q.db.QueryRow(ctx, getUserById, pUserid)
	var i TblUser
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.AccountType,
		&i.IsActive,
		&i.IsGlobalAdmin,
		&i.PermissionsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserCredentialByEmail = `-- name: GetUserCredentialByEmail :one
SELECT id, client_id, email, password_hash, account_type, is_global_admin, permissions_version FROM udf_GetUserCredentialByEmail($1)
`

func (q *Queries) GetUserCredentialByEmail(ctx context.Context, pEmail string) (VwUsercredential, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByEmail, pEmail)
	var i VwUsercredential
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.AccountType,
		&i.IsGlobalAdmin,
		&i.PermissionsVersion,
	)
	return i, err
}

const getUserFreshness = `-- name: GetUserFreshness :one
SELECT id, permissions_version, is_active, deleted_at FROM udf_GetUserFreshness($1)
`

func (q *Queries) GetUserFreshness(ctx context.Context, pUserid string) (VwUserfreshness, error) {
	row := q.db.QueryRow(ctx, getUserFreshness, pUserid)
	var i VwUserfreshness
	err := row.Scan(
		&i.ID,
		&i.PermissionsVersion,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const getUserIdentityForToken = `-- name: GetUserIdentityForToken :one
SELECT id, client_id, email, is_global_admin, permissions_version FROM udf_GetUserIdentityForToken($1)
`

func (q *Queries) GetUserIdentityForToken(ctx context.Context, pUserid string) (VwUseridentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityForToken, pUserid)
	var i VwUseridentity
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.PermissionsVersion,
	)
	return i, err
}

const getUserTenantScoped = `-- name: GetUserTenantScoped :one
SELECT id, client_id, email, account_type, is_active, is_global_admin, permissions_version, created_at, updated_at FROM udf_GetUserTenantScoped($1, $2)
`

type GetUserTenantScopedParams struct {
	PUserid   string
	PClientid string
}

func (q *Queries) GetUserTenantScoped(ctx context.Context, arg GetUserTenantScopedParams) (VwUsertenantscoped, error) {
	row := q.db.QueryRow(ctx, getUserTenantScoped, arg.PUserid, arg.PClientid)
	var i VwUsertenantscoped
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.AccountType,
		&i.IsActive,
		&i.IsGlobalAdmin,
		&i.PermissionsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserFeatures = `-- name: ListUserFeatures :many
SELECT udf_listuserfeatures FROM udf_ListUserFeatures($1, $2)
`

type ListUserFeaturesParams struct {
	PClientid string
	PUserid   string
}

func (q *Queries) ListUserFeatures(ctx context.Context, arg ListUserFeaturesParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listUserFeatures, arg.PClientid, arg.PUserid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var udf_listuserfeatures pgtype.Text
		if err := rows.Scan(&udf_listuserfeatures); err != nil {
			return nil, err
		}
		items = append(items, udf_listuserfeatures)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT user_id, client_id, group_id, group_name, assigned_at FROM udf_ListUserGroups(
    $1,
    $2::text[]
)
`

type ListUserGroupsParams struct {
	ClientID string
	UserIds  []string
}

func (q *Queries) ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]VwUsergroupmembership, error) {
	rows, err := q.db.Query(ctx, listUserGroups, arg.ClientID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwUsergroupmembership{}
	for rows.Next() {
		var i VwUsergroupmembership
		if err := rows.Scan(
			&i.UserID,
			&i.ClientID,
			&i.GroupID,
			&i.GroupName,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProductRoles = `-- name: ListUserProductRoles :many
SELECT user_id, client_id, product_id, product_key, product_name, role_name, valid_until FROM udf_ListUserProductRoles($1, $2)
`

type ListUserProductRolesParams struct {
	PUserid   string
	PClientid string
}

func (q *Queries) ListUserProductRoles(ctx context.Context, arg ListUserProductRolesParams) ([]VwUserproductrole, error) {
	rows, err := q.db.Query(ctx, listUserProductRoles, arg.PUserid, arg.PClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwUserproductrole{}
	for rows.Next() {
		var i VwUserproductrole
		if err := rows.Scan(
			&i.UserID,
			&i.ClientID,
			&i.ProductID,
			&i.ProductKey,
			&i.ProductName,
			&i.RoleName,
			&i.ValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, client_id, email, account_type, is_active, is_global_admin, permissions_version, created_at, updated_at FROM udf_ListUsers(
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type ListUsersParams struct {
	ClientID      string
	Search        pgtype.Text
	CursorCreated pgtype.Timestamptz
	CursorID      pgtype.Text
	Take          int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]VwUserlistitem, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.ClientID,
		arg.Search,
		arg.CursorCreated,
		arg.CursorID,
		arg.Take,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwUserlistitem{}
	for rows.Next() {
		var i VwUserlistitem
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Email,
			&i.AccountType,
			&i.IsActive,
			&i.IsGlobalAdmin,
			&i.PermissionsVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
SELECT stp_SetUserActive($1, $2, $3)
`

type SetUserActiveParams struct {
	PUserid   string
	PClientid string
	PIsactive bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (int32, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.PUserid, arg.PClientid, arg.PIsactive)
	var stp_setuseractive int32
	err := row.Scan(&stp_setuseractive)
	return stp_setuseractive, err
}

const setUserPassword = `-- name: SetUserPassword :exec
CALL stp_SetUserPassword(
    $1,
    $2,
    $3
)
`

type SetUserPasswordParams struct {
	UserID       string
	ClientID     string
	PasswordHash string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.UserID, arg.ClientID, arg.PasswordHash)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
CALL stp_SoftDeleteUser($1, $2)
`

type SoftDeleteUserParams struct {
	PUserid   string
	PClientid string
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.PUserid, arg.PClientid)
	return err
}

const userCursorPosition = `-- name: UserCursorPosition :one
SELECT created_at FROM (SELECT udf_UserCursorPosition($1, $2) AS created_at) t
WHERE created_at IS NOT NULL
`

type UserCursorPositionParams struct {
	PUserid   string
	PClientid string
}

// Filtered so an unresolvable cursor yields zero rows (see entitlements.sql).
func (q *Queries) UserCursorPosition(ctx context.Context, arg UserCursorPositionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, userCursorPosition, arg.PUserid, arg.PClientid)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const userIdByEmail = `-- name: UserIdByEmail :one
SELECT id FROM (SELECT udf_UserIdByEmail($1, $2) AS id) t WHERE id IS NOT NULL
`

type UserIdByEmailParams struct {
	PClientid string
	PEmail    string
}

// Filtered so an unknown address yields zero rows (see entitlements.sql).
func (q *Queries) UserIdByEmail(ctx context.Context, arg UserIdByEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, userIdByEmail, arg.PClientid, arg.PEmail)
	var id string
	err := row.Scan(&id)
	return id, err
}
