// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: alora/demo/inventory/v1/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item is one thing in the inventory.
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_alora_demo_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListItemsRequest asks for every item.
type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_alora_demo_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

// ListItemsResponse is the inventory, and who asked.
type ListItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// The API client the token was issued to (aci_…).
	Caller        string `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_alora_demo_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsResponse) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

// AddItemRequest names the item to add.
type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_alora_demo_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// AddItemResponse is the item added.
type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alora_demo_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_alora_demo_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_alora_demo_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_alora_demo_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"'alora/demo/inventory/v1/inventory.proto\x12\x17alora.demo.inventory.v1\"*\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x12\n" +
	"\x10ListItemsRequest\"`\n" +
	"\x11ListItemsResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.alora.demo.inventory.v1.ItemR\x05items\x12\x16\n" +
	"\x06caller\x18\x02 \x01(\tR\x06caller\"$\n" +
	"\x0eAddItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x0fAddItemResponse\x121\n" +
	"\x04item\x18\x01 \x01(\v2\x1d.alora.demo.inventory.v1.ItemR\x04item2\xd4\x01\n" +
	"\x10InventoryService\x12b\n" +
	"\tListItems\x12).alora.demo.inventory.v1.ListItemsRequest\x1a*.alora.demo.inventory.v1.ListItemsResponse\x12\\\n" +
	"\aAddItem\x12'.alora.demo.inventory.v1.AddItemRequest\x1a(.alora.demo.inventory.v1.AddItemResponseBZZXgithub.com/prasath-23/Alora-Auth/alora-auth-go/examples/grpcdemo/inventorypb;inventorypbb\x06proto3"

var (
	file_alora_demo_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_alora_demo_inventory_v1_inventory_proto_rawDescData []byte
)

func file_alora_demo_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_alora_demo_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_alora_demo_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alora_demo_inventory_v1_inventory_proto_rawDesc), len(file_alora_demo_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_alora_demo_inventory_v1_inventory_proto_rawDescData
}

var file_alora_demo_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_alora_demo_inventory_v1_inventory_proto_goTypes = []any{
	(*Item)(nil),              // 0: alora.demo.inventory.v1.Item
	(*ListItemsRequest)(nil),  // 1: alora.demo.inventory.v1.ListItemsRequest
	(*ListItemsResponse)(nil), // 2: alora.demo.inventory.v1.ListItemsResponse
	(*AddItemRequest)(nil),    // 3: alora.demo.inventory.v1.AddItemRequest
	(*AddItemResponse)(nil),   // 4: alora.demo.inventory.v1.AddItemResponse
}
var file_alora_demo_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: alora.demo.inventory.v1.ListItemsResponse.items:type_name -> alora.demo.inventory.v1.Item
	0, // 1: alora.demo.inventory.v1.AddItemResponse.item:type_name -> alora.demo.inventory.v1.Item
	1, // 2: alora.demo.inventory.v1.InventoryService.ListItems:input_type -> alora.demo.inventory.v1.ListItemsRequest
	3, // 3: alora.demo.inventory.v1.InventoryService.AddItem:input_type -> alora.demo.inventory.v1.AddItemRequest
	2, // 4: alora.demo.inventory.v1.InventoryService.ListItems:output_type -> alora.demo.inventory.v1.ListItemsResponse
	4, // 5: alora.demo.inventory.v1.InventoryService.AddItem:output_type -> alora.demo.inventory.v1.AddItemResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alora_demo_inventory_v1_inventory_proto_init() }
func file_alora_demo_inventory_v1_inventory_proto_init() {
	if File_alora_demo_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alora_demo_inventory_v1_inventory_proto_rawDesc), len(file_alora_demo_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alora_demo_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_alora_demo_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_alora_demo_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_alora_demo_inventory_v1_inventory_proto = out.File
	file_alora_demo_inventory_v1_inventory_proto_goTypes = nil
	file_alora_demo_inventory_v1_inventory_proto_depIdxs = nil
}
