// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEffectiveRoles = `-- name: ListEffectiveRoles :many

SELECT udf_listeffectiveroles FROM udf_ListEffectiveRoles($1, $2, $3)
`

type ListEffectiveRolesParams struct {
	PUserid    string
	PClientid  string
	PProductid string
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: effective product access
//
// vw_EffectiveProductRole is the single definition of "may use this product":
// direct grants plus group grants, only for live users, active tenants and
// products, and live subscriptions.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) ListEffectiveRoles(ctx context.Context, arg ListEffectiveRolesParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listEffectiveRoles, arg.PUserid, arg.PClientid, arg.PProductid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var udf_listeffectiveroles pgtype.Text
		if err := rows.Scan(&udf_listeffectiveroles); err != nil {
			return nil, err
		}
		items = append(items, udf_listeffectiveroles)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserApps = `-- name: ListUserApps :many
SELECT user_id, client_id, product_id, product_key, product_name, product_description, base_url, initiate_login_uri, roles FROM udf_ListUserApps($1, $2)
`

type ListUserAppsParams struct {
	PUserid   string
	PClientid string
}

func (q *Queries) ListUserApps(ctx context.Context, arg ListUserAppsParams) ([]VwUserapp, error) {
	rows, err := q.db.Query(ctx, listUserApps, arg.PUserid, arg.PClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwUserapp{}
	for rows.Next() {
		var i VwUserapp
		if err := rows.Scan(
			&i.UserID,
			&i.ClientID,
			&i.ProductID,
			&i.ProductKey,
			&i.ProductName,
			&i.ProductDescription,
			&i.BaseUrl,
			&i.InitiateLoginUri,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEffectiveAccess = `-- name: ListUserEffectiveAccess :many
SELECT user_id, client_id, product_id, product_key, product_name, role_name, source, group_id FROM udf_ListUserEffectiveAccess($1, $2)
`

type ListUserEffectiveAccessParams struct {
	PUserid   string
	PClientid string
}

func (q *Queries) ListUserEffectiveAccess(ctx context.Context, arg ListUserEffectiveAccessParams) ([]VwEffectiveproductrole, error) {
	rows, err := q.db.Query(ctx, listUserEffectiveAccess, arg.PUserid, arg.PClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwEffectiveproductrole{}
	for rows.Next() {
		var i VwEffectiveproductrole
		if err := rows.Scan(
			&i.UserID,
			&i.ClientID,
			&i.ProductID,
			&i.ProductKey,
			&i.ProductName,
			&i.RoleName,
			&i.Source,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
