// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apiclients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiClient = `-- name: CreateApiClient :one

SELECT id, client_id, name, description, is_active, created_by_user_id, created_by_owner_id, last_used_at, created_at, updated_at FROM stp_CreateApiClient(
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateApiClientParams struct {
	ClientID         string
	Name             string
	Description      pgtype.Text
	CreatedByUserID  pgtype.Text
	CreatedByOwnerID pgtype.Text
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: API clients — applications' identities, where their credential
// may be used (CLIENT scopes), the products they may get a token for, and their
// secrets
//
// Every read and write is tenant-scoped by (id, client_id) inside the routine,
// so a foreign id finds and changes nothing. Secrets are stored as hashes only,
// and no read here returns one.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) CreateApiClient(ctx context.Context, arg CreateApiClientParams) (TblApiClient, error) {
	row := q.db.QueryRow(ctx, createApiClient,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.CreatedByUserID,
		arg.CreatedByOwnerID,
	)
	var i TblApiClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedByOwnerID,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApiClientSecret = `-- name: CreateApiClientSecret :one
SELECT id, api_client_id, client_id, prefix, expires_at, revoked_at, last_used_at, created_by_user_id, created_by_owner_id, created_at, is_live FROM stp_CreateApiClientSecret(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateApiClientSecretParams struct {
	ApiClientID      string
	ClientID         string
	SecretHash       string
	Prefix           string
	ExpiresAt        pgtype.Timestamptz
	CreatedByUserID  pgtype.Text
	CreatedByOwnerID pgtype.Text
}

func (q *Queries) CreateApiClientSecret(ctx context.Context, arg CreateApiClientSecretParams) (VwApiclientsecret, error) {
	row := q.db.QueryRow(ctx, createApiClientSecret,
		arg.ApiClientID,
		arg.ClientID,
		arg.SecretHash,
		arg.Prefix,
		arg.ExpiresAt,
		arg.CreatedByUserID,
		arg.CreatedByOwnerID,
	)
	var i VwApiclientsecret
	err := row.Scan(
		&i.ID,
		&i.ApiClientID,
		&i.ClientID,
		&i.Prefix,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.CreatedByOwnerID,
		&i.CreatedAt,
		&i.IsLive,
	)
	return i, err
}

const deleteApiClient = `-- name: DeleteApiClient :one
SELECT stp_DeleteApiClient($1, $2)
`

type DeleteApiClientParams struct {
	ApiClientID string
	ClientID    string
}

func (q *Queries) DeleteApiClient(ctx context.Context, arg DeleteApiClientParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteApiClient, arg.ApiClientID, arg.ClientID)
	var stp_deleteapiclient int32
	err := row.Scan(&stp_deleteapiclient)
	return stp_deleteapiclient, err
}

const getApiClient = `-- name: GetApiClient :one
SELECT id, client_id, company_name, name, description, is_active, created_by_user_id, created_by_owner_id, last_used_at, created_at, updated_at, scopes, products, live_secrets FROM udf_GetApiClient($1, $2)
`

type GetApiClientParams struct {
	ApiClientID string
	ClientID    string
}

func (q *Queries) GetApiClient(ctx context.Context, arg GetApiClientParams) (VwApiclientsummary, error) {
	row := q.db.QueryRow(ctx, getApiClient, arg.ApiClientID, arg.ClientID)
	var i VwApiclientsummary
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CompanyName,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedByOwnerID,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scopes,
		&i.Products,
		&i.LiveSecrets,
	)
	return i, err
}

const getApiClientGrant = `-- name: GetApiClientGrant :one
SELECT api_client_id, client_id, product_id, product_key, usable, scopes FROM udf_GetApiClientGrant($1, $2)
`

type GetApiClientGrantParams struct {
	ApiClientID string
	ProductKey  string
}

func (q *Queries) GetApiClientGrant(ctx context.Context, arg GetApiClientGrantParams) (VwApiclientgrant, error) {
	row := q.db.QueryRow(ctx, getApiClientGrant, arg.ApiClientID, arg.ProductKey)
	var i VwApiclientgrant
	err := row.Scan(
		&i.ApiClientID,
		&i.ClientID,
		&i.ProductID,
		&i.ProductKey,
		&i.Usable,
		&i.Scopes,
	)
	return i, err
}

const getOAuthClientCredentials = `-- name: GetOAuthClientCredentials :many
SELECT kind, oauth_client_id, product_key, company_id, secret_id, secret_hash, is_active FROM udf_GetOAuthClientCredentials($1)
`

func (q *Queries) GetOAuthClientCredentials(ctx context.Context, pOauthclientid string) ([]VwOauthclientcredential, error) {
	rows, err := q.db.Query(ctx, getOAuthClientCredentials, pOauthclientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwOauthclientcredential{}
	for rows.Next() {
		var i VwOauthclientcredential
		if err := rows.Scan(
			&i.Kind,
			&i.OauthClientID,
			&i.ProductKey,
			&i.CompanyID,
			&i.SecretID,
			&i.SecretHash,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isApiClientSecretLive = `-- name: IsApiClientSecretLive :one
SELECT udf_IsApiClientSecretLive($1, $2)
`

type IsApiClientSecretLiveParams struct {
	SecretID    string
	ApiClientID string
}

func (q *Queries) IsApiClientSecretLive(ctx context.Context, arg IsApiClientSecretLiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, isApiClientSecretLive, arg.SecretID, arg.ApiClientID)
	var udf_isapiclientsecretlive bool
	err := row.Scan(&udf_isapiclientsecretlive)
	return udf_isapiclientsecretlive, err
}

const listAllApiClients = `-- name: ListAllApiClients :many
SELECT id, client_id, company_name, name, description, is_active, created_by_user_id, created_by_owner_id, last_used_at, created_at, updated_at, scopes, products, live_secrets FROM udf_ListAllApiClients()
`

func (q *Queries) ListAllApiClients(ctx context.Context) ([]VwApiclientsummary, error) {
	rows, err := q.db.Query(ctx, listAllApiClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwApiclientsummary{}
	for rows.Next() {
		var i VwApiclientsummary
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CompanyName,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedByOwnerID,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scopes,
			&i.Products,
			&i.LiveSecrets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiClientProductChoices = `-- name: ListApiClientProductChoices :many
SELECT id, client_id, product_id, is_active, seat_limit, starts_at, ends_at, created_at, product_key, product_name, product_description, product_base_url, product_is_active, product_accepts_api_clients FROM udf_ListApiClientProductChoices($1)
`

func (q *Queries) ListApiClientProductChoices(ctx context.Context, pClientid string) ([]VwClientproductdetail, error) {
	rows, err := q.db.Query(ctx, listApiClientProductChoices, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwClientproductdetail{}
	for rows.Next() {
		var i VwClientproductdetail
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProductID,
			&i.IsActive,
			&i.SeatLimit,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.ProductKey,
			&i.ProductName,
			&i.ProductDescription,
			&i.ProductBaseUrl,
			&i.ProductIsActive,
			&i.ProductAcceptsApiClients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiClientSecrets = `-- name: ListApiClientSecrets :many
SELECT id, api_client_id, client_id, prefix, expires_at, revoked_at, last_used_at, created_by_user_id, created_by_owner_id, created_at, is_live FROM udf_ListApiClientSecrets($1, $2)
`

type ListApiClientSecretsParams struct {
	ApiClientID string
	ClientID    string
}

func (q *Queries) ListApiClientSecrets(ctx context.Context, arg ListApiClientSecretsParams) ([]VwApiclientsecret, error) {
	rows, err := q.db.Query(ctx, listApiClientSecrets, arg.ApiClientID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwApiclientsecret{}
	for rows.Next() {
		var i VwApiclientsecret
		if err := rows.Scan(
			&i.ID,
			&i.ApiClientID,
			&i.ClientID,
			&i.Prefix,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedByUserID,
			&i.CreatedByOwnerID,
			&i.CreatedAt,
			&i.IsLive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiClients = `-- name: ListApiClients :many
SELECT id, client_id, company_name, name, description, is_active, created_by_user_id, created_by_owner_id, last_used_at, created_at, updated_at, scopes, products, live_secrets FROM udf_ListApiClients($1)
`

func (q *Queries) ListApiClients(ctx context.Context, pClientid string) ([]VwApiclientsummary, error) {
	rows, err := q.db.Query(ctx, listApiClients, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwApiclientsummary{}
	for rows.Next() {
		var i VwApiclientsummary
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CompanyName,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedByOwnerID,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scopes,
			&i.Products,
			&i.LiveSecrets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiClientSecret = `-- name: RevokeApiClientSecret :one
SELECT stp_RevokeApiClientSecret($1, $2, $3)
`

type RevokeApiClientSecretParams struct {
	SecretID    string
	ApiClientID string
	ClientID    string
}

func (q *Queries) RevokeApiClientSecret(ctx context.Context, arg RevokeApiClientSecretParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeApiClientSecret, arg.SecretID, arg.ApiClientID, arg.ClientID)
	var stp_revokeapiclientsecret int32
	err := row.Scan(&stp_revokeapiclientsecret)
	return stp_revokeapiclientsecret, err
}

const setApiClientProducts = `-- name: SetApiClientProducts :one
SELECT stp_SetApiClientProducts(
    $1,
    $2,
    $3::text[]
)
`

type SetApiClientProductsParams struct {
	ApiClientID string
	ClientID    string
	ProductIds  []string
}

func (q *Queries) SetApiClientProducts(ctx context.Context, arg SetApiClientProductsParams) (int32, error) {
	row := q.db.QueryRow(ctx, setApiClientProducts, arg.ApiClientID, arg.ClientID, arg.ProductIds)
	var stp_setapiclientproducts int32
	err := row.Scan(&stp_setapiclientproducts)
	return stp_setapiclientproducts, err
}

const setApiClientScopes = `-- name: SetApiClientScopes :one
SELECT stp_SetApiClientScopes(
    $1,
    $2,
    $3::text[]
)
`

type SetApiClientScopesParams struct {
	ApiClientID string
	ClientID    string
	Scopes      []string
}

func (q *Queries) SetApiClientScopes(ctx context.Context, arg SetApiClientScopesParams) (int32, error) {
	row := q.db.QueryRow(ctx, setApiClientScopes, arg.ApiClientID, arg.ClientID, arg.Scopes)
	var stp_setapiclientscopes int32
	err := row.Scan(&stp_setapiclientscopes)
	return stp_setapiclientscopes, err
}

const touchApiClientSecret = `-- name: TouchApiClientSecret :exec
CALL stp_TouchApiClientSecret($1, $2)
`

type TouchApiClientSecretParams struct {
	SecretID    string
	ApiClientID string
}

func (q *Queries) TouchApiClientSecret(ctx context.Context, arg TouchApiClientSecretParams) error {
	_, err := q.db.Exec(ctx, touchApiClientSecret, arg.SecretID, arg.ApiClientID)
	return err
}

const updateApiClient = `-- name: UpdateApiClient :one
SELECT id, client_id, name, description, is_active, created_by_user_id, created_by_owner_id, last_used_at, created_at, updated_at FROM stp_UpdateApiClient(
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type UpdateApiClientParams struct {
	ApiClientID string
	ClientID    string
	Name        string
	Description pgtype.Text
	IsActive    bool
}

func (q *Queries) UpdateApiClient(ctx context.Context, arg UpdateApiClientParams) (TblApiClient, error) {
	row := q.db.QueryRow(ctx, updateApiClient,
		arg.ApiClientID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i TblApiClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedByOwnerID,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
