// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clientNameById = `-- name: ClientNameById :one
SELECT name FROM (SELECT udf_ClientNameById($1) AS name) t WHERE name IS NOT NULL
`

// Filtered so an unknown tenant yields zero rows (see entitlements.sql).
func (q *Queries) ClientNameById(ctx context.Context, pClientid string) (string, error) {
	row := q.db.QueryRow(ctx, clientNameById, pClientid)
	var name string
	err := row.Scan(&name)
	return name, err
}

const createClient = `-- name: CreateClient :one
SELECT id, name, domain, domain_verified_at, subscription_status, max_seats, is_active, is_platform, created_at, updated_at FROM stp_CreateClient(
    $1,
    $2,
    $3::"SubscriptionStatus",
    $4,
    $5,
    $6
)
`

type CreateClientParams struct {
	Name               string
	Domain             pgtype.Text
	SubscriptionStatus SubscriptionStatus
	MaxSeats           pgtype.Int4
	IsActive           bool
	IsPlatform         bool
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (TblClient, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.Domain,
		arg.SubscriptionStatus,
		arg.MaxSeats,
		arg.IsActive,
		arg.IsPlatform,
	)
	var i TblClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.DomainVerifiedAt,
		&i.SubscriptionStatus,
		&i.MaxSeats,
		&i.IsActive,
		&i.IsPlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
SELECT id, key, name, description, base_url, initiate_login_uri, client_secret_hash, secret_rotated_at, is_active, accepts_api_clients, created_at, updated_at FROM stp_CreateProduct(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateProductParams struct {
	Key               string
	Name              string
	Description       pgtype.Text
	BaseUrl           pgtype.Text
	InitiateLoginUri  pgtype.Text
	IsActive          bool
	AcceptsApiClients bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (TblProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.InitiateLoginUri,
		arg.IsActive,
		arg.AcceptsApiClients,
	)
	var i TblProduct
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.InitiateLoginUri,
		&i.ClientSecretHash,
		&i.SecretRotatedAt,
		&i.IsActive,
		&i.AcceptsApiClients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientById = `-- name: GetClientById :one

SELECT id, name, domain, domain_verified_at, subscription_status, max_seats, is_active, is_platform, created_at, updated_at FROM udf_GetClientById($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: tenants and the product catalogue
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetClientById(ctx context.Context, pClientid string) (TblClient, error) {
	row := q.db.QueryRow(ctx, getClientById, pClientid)
	var i TblClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.DomainVerifiedAt,
		&i.SubscriptionStatus,
		&i.MaxSeats,
		&i.IsActive,
		&i.IsPlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, key, name, description, base_url, initiate_login_uri, client_secret_hash, secret_rotated_at, is_active, accepts_api_clients, created_at, updated_at FROM udf_GetProductById($1, $2)
`

type GetProductByIdParams struct {
	PProductid  string
	PActiveonly bool
}

func (q *Queries) GetProductById(ctx context.Context, arg GetProductByIdParams) (TblProduct, error) {
	row := q.db.QueryRow(ctx, getProductById, arg.PProductid, arg.PActiveonly)
	var i TblProduct
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.InitiateLoginUri,
		&i.ClientSecretHash,
		&i.SecretRotatedAt,
		&i.IsActive,
		&i.AcceptsApiClients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductClient = `-- name: GetProductClient :one
SELECT id, key, name, description, base_url, initiate_login_uri, is_active, accepts_api_clients, has_secret, secret_rotated_at, created_at, updated_at FROM udf_GetProductClient($1)
`

func (q *Queries) GetProductClient(ctx context.Context, pProductid string) (VwProductclient, error) {
	row := q.db.QueryRow(ctx, getProductClient, pProductid)
	var i VwProductclient
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.InitiateLoginUri,
		&i.IsActive,
		&i.AcceptsApiClients,
		&i.HasSecret,
		&i.SecretRotatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductClientCredential = `-- name: GetProductClientCredential :one
SELECT id, key, is_active, client_secret_hash FROM udf_GetProductClientCredential($1)
`

func (q *Queries) GetProductClientCredential(ctx context.Context, pProductid string) (VwProductclientcredential, error) {
	row := q.db.QueryRow(ctx, getProductClientCredential, pProductid)
	var i VwProductclientcredential
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.IsActive,
		&i.ClientSecretHash,
	)
	return i, err
}

const isRedirectUriRegistered = `-- name: IsRedirectUriRegistered :one
SELECT udf_IsRedirectUriRegistered($1, $2)
`

type IsRedirectUriRegisteredParams struct {
	PProductid   string
	PRedirecturi string
}

func (q *Queries) IsRedirectUriRegistered(ctx context.Context, arg IsRedirectUriRegisteredParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRedirectUriRegistered, arg.PProductid, arg.PRedirecturi)
	var udf_isredirecturiregistered bool
	err := row.Scan(&udf_isredirecturiregistered)
	return udf_isredirecturiregistered, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, key, name, description, base_url, initiate_login_uri, client_secret_hash, secret_rotated_at, is_active, accepts_api_clients, created_at, updated_at FROM udf_ListActiveProducts()
`

func (q *Queries) ListActiveProducts(ctx context.Context) ([]TblProduct, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblProduct{}
	for rows.Next() {
		var i TblProduct
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.InitiateLoginUri,
			&i.ClientSecretHash,
			&i.SecretRotatedAt,
			&i.IsActive,
			&i.AcceptsApiClients,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, domain, domain_verified_at, subscription_status, max_seats, is_active, is_platform, created_at, updated_at, user_count FROM udf_ListCompanies()
`

func (q *Queries) ListCompanies(ctx context.Context) ([]VwCompanylistitem, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwCompanylistitem{}
	for rows.Next() {
		var i VwCompanylistitem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.DomainVerifiedAt,
			&i.SubscriptionStatus,
			&i.MaxSeats,
			&i.IsActive,
			&i.IsPlatform,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductRedirectUris = `-- name: ListProductRedirectUris :many
SELECT product_id, redirect_uri, created_at FROM udf_ListProductRedirectUris($1)
`

func (q *Queries) ListProductRedirectUris(ctx context.Context, pProductid string) ([]TblProductRedirectUri, error) {
	rows, err := q.db.Query(ctx, listProductRedirectUris, pProductid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblProductRedirectUri{}
	for rows.Next() {
		var i TblProductRedirectUri
		if err := rows.Scan(&i.ProductID, &i.RedirectUri, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductRoles = `-- name: ListProductRoles :many
SELECT product_id, role_name, description, created_at FROM udf_ListProductRoles($1)
`

func (q *Queries) ListProductRoles(ctx context.Context, pProductid string) ([]TblProductRole, error) {
	rows, err := q.db.Query(ctx, listProductRoles, pProductid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblProductRole{}
	for rows.Next() {
		var i TblProductRole
		if err := rows.Scan(
			&i.ProductID,
			&i.RoleName,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, key, name, description, base_url, initiate_login_uri, is_active, accepts_api_clients, has_secret, secret_rotated_at, created_at, updated_at FROM udf_ListProducts()
`

func (q *Queries) ListProducts(ctx context.Context) ([]VwProductclient, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwProductclient{}
	for rows.Next() {
		var i VwProductclient
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.InitiateLoginUri,
			&i.IsActive,
			&i.AcceptsApiClients,
			&i.HasSecret,
			&i.SecretRotatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productKeyById = `-- name: ProductKeyById :one
SELECT key FROM (SELECT udf_ProductKeyById($1) AS key) t WHERE key IS NOT NULL
`

// Filtered so an unknown product yields zero rows (see entitlements.sql).
func (q *Queries) ProductKeyById(ctx context.Context, pProductid string) (string, error) {
	row := q.db.QueryRow(ctx, productKeyById, pProductid)
	var key string
	err := row.Scan(&key)
	return key, err
}

const setClientDomain = `-- name: SetClientDomain :one
SELECT id, name, domain, domain_verified_at, subscription_status, max_seats, is_active, is_platform, created_at, updated_at FROM stp_SetClientDomain(
    $1,
    $2,
    $3
)
`

type SetClientDomainParams struct {
	ClientID string
	Domain   pgtype.Text
	Verified bool
}

func (q *Queries) SetClientDomain(ctx context.Context, arg SetClientDomainParams) (TblClient, error) {
	row := q.db.QueryRow(ctx, setClientDomain, arg.ClientID, arg.Domain, arg.Verified)
	var i TblClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.DomainVerifiedAt,
		&i.SubscriptionStatus,
		&i.MaxSeats,
		&i.IsActive,
		&i.IsPlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setProductClientSecret = `-- name: SetProductClientSecret :one
SELECT stp_SetProductClientSecret($1, $2)
`

type SetProductClientSecretParams struct {
	PProductid  string
	PSecrethash string
}

func (q *Queries) SetProductClientSecret(ctx context.Context, arg SetProductClientSecretParams) (int32, error) {
	row := q.db.QueryRow(ctx, setProductClientSecret, arg.PProductid, arg.PSecrethash)
	var stp_setproductclientsecret int32
	err := row.Scan(&stp_setproductclientsecret)
	return stp_setproductclientsecret, err
}

const setProductRedirectUris = `-- name: SetProductRedirectUris :one
SELECT stp_SetProductRedirectUris(
    $1,
    $2::text[]
)
`

type SetProductRedirectUrisParams struct {
	ProductID    string
	RedirectUris []string
}

func (q *Queries) SetProductRedirectUris(ctx context.Context, arg SetProductRedirectUrisParams) (int32, error) {
	row := q.db.QueryRow(ctx, setProductRedirectUris, arg.ProductID, arg.RedirectUris)
	var stp_setproductredirecturis int32
	err := row.Scan(&stp_setproductredirecturis)
	return stp_setproductredirecturis, err
}

const setProductRoles = `-- name: SetProductRoles :one
SELECT stp_SetProductRoles(
    $1,
    $2::text[]
)
`

type SetProductRolesParams struct {
	ProductID string
	RoleNames []string
}

func (q *Queries) SetProductRoles(ctx context.Context, arg SetProductRolesParams) (int32, error) {
	row := q.db.QueryRow(ctx, setProductRoles, arg.ProductID, arg.RoleNames)
	var stp_setproductroles int32
	err := row.Scan(&stp_setproductroles)
	return stp_setproductroles, err
}

const updateClient = `-- name: UpdateClient :one
SELECT id, name, domain, domain_verified_at, subscription_status, max_seats, is_active, is_platform, created_at, updated_at FROM stp_UpdateClient(
    $1,
    $2,
    $3,
    $4::"SubscriptionStatus",
    $5,
    $6
)
`

type UpdateClientParams struct {
	ClientID           string
	Name               string
	DomainVerifiedAt   pgtype.Timestamptz
	SubscriptionStatus SubscriptionStatus
	MaxSeats           pgtype.Int4
	IsActive           bool
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (TblClient, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ClientID,
		arg.Name,
		arg.DomainVerifiedAt,
		arg.SubscriptionStatus,
		arg.MaxSeats,
		arg.IsActive,
	)
	var i TblClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.DomainVerifiedAt,
		&i.SubscriptionStatus,
		&i.MaxSeats,
		&i.IsActive,
		&i.IsPlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
SELECT id, key, name, description, base_url, initiate_login_uri, client_secret_hash, secret_rotated_at, is_active, accepts_api_clients, created_at, updated_at FROM stp_UpdateProduct(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type UpdateProductParams struct {
	ProductID         string
	Name              string
	Description       pgtype.Text
	BaseUrl           pgtype.Text
	InitiateLoginUri  pgtype.Text
	IsActive          bool
	AcceptsApiClients pgtype.Bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (TblProduct, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.InitiateLoginUri,
		arg.IsActive,
		arg.AcceptsApiClients,
	)
	var i TblProduct
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.InitiateLoginUri,
		&i.ClientSecretHash,
		&i.SecretRotatedAt,
		&i.IsActive,
		&i.AcceptsApiClients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
