// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlements.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeSubscriptionId = `-- name: ActiveSubscriptionId :one

SELECT id FROM (SELECT udf_ActiveSubscriptionId($1, $2) AS id) t WHERE id IS NOT NULL
`

type ActiveSubscriptionIdParams struct {
	PClientid  string
	PProductid string
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: subscriptions and direct product-role grants
// ─────────────────────────────────────────────────────────────────────────────
// Filtered so a NULL (no subscription) yields ZERO ROWS rather than one NULL
// row: a scalar function always returns a row, and the caller distinguishes
// "not found" by pgx.ErrNoRows.
func (q *Queries) ActiveSubscriptionId(ctx context.Context, arg ActiveSubscriptionIdParams) (string, error) {
	row := q.db.QueryRow(ctx, activeSubscriptionId, arg.PClientid, arg.PProductid)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteProductPermission = `-- name: DeleteProductPermission :one
SELECT stp_DeleteProductPermission($1, $2, $3)
`

type DeleteProductPermissionParams struct {
	PUserid    string
	PClientid  string
	PProductid string
}

func (q *Queries) DeleteProductPermission(ctx context.Context, arg DeleteProductPermissionParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteProductPermission, arg.PUserid, arg.PClientid, arg.PProductid)
	var stp_deleteproductpermission int32
	err := row.Scan(&stp_deleteproductpermission)
	return stp_deleteproductpermission, err
}

const getProductPermission = `-- name: GetProductPermission :one
SELECT user_id, client_id, product_id, product_key, product_name, role_name, valid_until FROM udf_GetProductPermission($1, $2, $3)
`

type GetProductPermissionParams struct {
	PUserid    string
	PClientid  string
	PProductid string
}

func (q *Queries) GetProductPermission(ctx context.Context, arg GetProductPermissionParams) (VwUserproductrole, error) {
	row := q.db.QueryRow(ctx, getProductPermission, arg.PUserid, arg.PClientid, arg.PProductid)
	var i VwUserproductrole
	err := row.Scan(
		&i.UserID,
		&i.ClientID,
		&i.ProductID,
		&i.ProductKey,
		&i.ProductName,
		&i.RoleName,
		&i.ValidUntil,
	)
	return i, err
}

const listClientProducts = `-- name: ListClientProducts :many
SELECT id, client_id, product_id, is_active, seat_limit, starts_at, ends_at, created_at, product_key, product_name, product_description, product_base_url, product_is_active, product_accepts_api_clients FROM udf_ListClientProducts($1)
`

func (q *Queries) ListClientProducts(ctx context.Context, pClientid string) ([]VwClientproductdetail, error) {
	rows, err := q.db.Query(ctx, listClientProducts, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwClientproductdetail{}
	for rows.Next() {
		var i VwClientproductdetail
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProductID,
			&i.IsActive,
			&i.SeatLimit,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.ProductKey,
			&i.ProductName,
			&i.ProductDescription,
			&i.ProductBaseUrl,
			&i.ProductIsActive,
			&i.ProductAcceptsApiClients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductPermission = `-- name: UpsertProductPermission :exec
CALL stp_UpsertProductPermission($1, $2, $3, $4, $5)
`

type UpsertProductPermissionParams struct {
	PUserid    string
	PClientid  string
	PProductid string
	PRolename  string
	PGrantedby string
}

func (q *Queries) UpsertProductPermission(ctx context.Context, arg UpsertProductPermissionParams) error {
	_, err := q.db.Exec(ctx, upsertProductPermission,
		arg.PUserid,
		arg.PClientid,
		arg.PProductid,
		arg.PRolename,
		arg.PGrantedby,
	)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :one
SELECT id, client_id, product_id, is_active, seat_limit, starts_at, ends_at, created_at FROM stp_UpsertSubscription(
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type UpsertSubscriptionParams struct {
	ClientID  string
	ProductID string
	IsActive  bool
	SeatLimit pgtype.Int4
	EndsAt    pgtype.Timestamptz
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (TblClientProduct, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.ClientID,
		arg.ProductID,
		arg.IsActive,
		arg.SeatLimit,
		arg.EndsAt,
	)
	var i TblClientProduct
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProductID,
		&i.IsActive,
		&i.SeatLimit,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}
