// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one

SELECT udf_HealthCheck()
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: readiness probe
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var udf_healthcheck int32
	err := row.Scan(&udf_healthcheck)
	return udf_healthcheck, err
}
