// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimInvitation = `-- name: ClaimInvitation :one
SELECT id, email, client_id, invited_by_user_id, invited_by_owner_id, token_hash, expires_at, status, accepted_at, accepted_by_user_id, revoked_at, revoked_by_user_id, created_at, updated_at FROM stp_ClaimInvitation(
    $1,
    $2
)
`

type ClaimInvitationParams struct {
	TokenHash        string
	AcceptedByUserID pgtype.Text
}

func (q *Queries) ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (TblInvitation, error) {
	row := q.db.QueryRow(ctx, claimInvitation, arg.TokenHash, arg.AcceptedByUserID)
	var i TblInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ClientID,
		&i.InvitedByUserID,
		&i.InvitedByOwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Status,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
SELECT id, email, client_id, invited_by_user_id, invited_by_owner_id, token_hash, expires_at, status, accepted_at, accepted_by_user_id, revoked_at, revoked_by_user_id, created_at, updated_at FROM stp_CreateInvitation(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateInvitationParams struct {
	Email            string
	ClientID         string
	InvitedByUserID  pgtype.Text
	InvitedByOwnerID pgtype.Text
	TokenHash        string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TblInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.ClientID,
		arg.InvitedByUserID,
		arg.InvitedByOwnerID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i TblInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ClientID,
		&i.InvitedByUserID,
		&i.InvitedByOwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Status,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitationGroup = `-- name: CreateInvitationGroup :exec
CALL stp_CreateInvitationGroup($1, $2, $3)
`

type CreateInvitationGroupParams struct {
	PInvitationid string
	PClientid     string
	PGroupid      string
}

func (q *Queries) CreateInvitationGroup(ctx context.Context, arg CreateInvitationGroupParams) error {
	_, err := q.db.Exec(ctx, createInvitationGroup, arg.PInvitationid, arg.PClientid, arg.PGroupid)
	return err
}

const expireInvitations = `-- name: ExpireInvitations :exec
CALL stp_ExpireInvitations($1)
`

func (q *Queries) ExpireInvitations(ctx context.Context, pBatchsize int32) error {
	_, err := q.db.Exec(ctx, expireInvitations, pBatchsize)
	return err
}

const getInvitationLoginPolicy = `-- name: GetInvitationLoginPolicy :one
SELECT id, client_id, name, allow_password, allow_google, sso_connection_id, priority, is_default, created_at, updated_at FROM udf_GetInvitationLoginPolicy($1, $2)
`

type GetInvitationLoginPolicyParams struct {
	PInvitationid string
	PClientid     string
}

func (q *Queries) GetInvitationLoginPolicy(ctx context.Context, arg GetInvitationLoginPolicyParams) (TblLoginPolicy, error) {
	row := q.db.QueryRow(ctx, getInvitationLoginPolicy, arg.PInvitationid, arg.PClientid)
	var i TblLoginPolicy
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.AllowPassword,
		&i.AllowGoogle,
		&i.SsoConnectionID,
		&i.Priority,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingInvitation = `-- name: GetPendingInvitation :one
SELECT id, email, client_id, invited_by_user_id, invited_by_owner_id, token_hash, expires_at, client_name FROM udf_GetPendingInvitation($1)
`

func (q *Queries) GetPendingInvitation(ctx context.Context, pTokenhash string) (VwPendinginvitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitation, pTokenhash)
	var i VwPendinginvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ClientID,
		&i.InvitedByUserID,
		&i.InvitedByOwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClientName,
	)
	return i, err
}

const getPendingInviteByEmail = `-- name: GetPendingInviteByEmail :one

SELECT id, email, client_id, invited_by_user_id, invited_by_owner_id, token_hash, expires_at, client_name FROM udf_GetPendingInviteByEmail($1, $2)
`

type GetPendingInviteByEmailParams struct {
	PClientid string
	PEmail    string
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: invitations
//
// The redeemable-invitation predicates (pending, unexpired, active tenant) live
// in vw_PendingInvitation, so every lookup below inherits them and no caller can
// accidentally honour a dead invitation.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetPendingInviteByEmail(ctx context.Context, arg GetPendingInviteByEmailParams) (VwPendinginvitation, error) {
	row := q.db.QueryRow(ctx, getPendingInviteByEmail, arg.PClientid, arg.PEmail)
	var i VwPendinginvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ClientID,
		&i.InvitedByUserID,
		&i.InvitedByOwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClientName,
	)
	return i, err
}

const listInvitationGroups = `-- name: ListInvitationGroups :many
SELECT invitation_id, client_id, group_id, group_name FROM udf_ListInvitationGroups($1)
`

func (q *Queries) ListInvitationGroups(ctx context.Context, pInvitationid string) ([]VwInvitationgroup, error) {
	rows, err := q.db.Query(ctx, listInvitationGroups, pInvitationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwInvitationgroup{}
	for rows.Next() {
		var i VwInvitationgroup
		if err := rows.Scan(
			&i.InvitationID,
			&i.ClientID,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, client_id, email, status, expires_at, created_at FROM udf_ListInvitations($1)
`

func (q *Queries) ListInvitations(ctx context.Context, pClientid string) ([]VwInvitationlistitem, error) {
	rows, err := q.db.Query(ctx, listInvitations, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwInvitationlistitem{}
	for rows.Next() {
		var i VwInvitationlistitem
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Email,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
SELECT stp_RevokeInvitation(
    $1,
    $2,
    $3
)
`

type RevokeInvitationParams struct {
	InvitationID    string
	ClientID        string
	RevokedByUserID pgtype.Text
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.InvitationID, arg.ClientID, arg.RevokedByUserID)
	var stp_revokeinvitation int32
	err := row.Scan(&stp_revokeinvitation)
	return stp_revokeinvitation, err
}

const setInvitationAcceptedBy = `-- name: SetInvitationAcceptedBy :exec
CALL stp_SetInvitationAcceptedBy($1, $2)
`

type SetInvitationAcceptedByParams struct {
	PInvitationid     string
	PAcceptedbyuserid string
}

func (q *Queries) SetInvitationAcceptedBy(ctx context.Context, arg SetInvitationAcceptedByParams) error {
	_, err := q.db.Exec(ctx, setInvitationAcceptedBy, arg.PInvitationid, arg.PAcceptedbyuserid)
	return err
}
