// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeEMAIL     AccountType = "EMAIL"
	AccountTypeOAUTHONLY AccountType = "OAUTH_ONLY"
	AccountTypeHYBRID    AccountType = "HYBRID"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type IdpProvider string

const (
	IdpProviderEMAIL     IdpProvider = "EMAIL"
	IdpProviderGOOGLE    IdpProvider = "GOOGLE"
	IdpProviderMICROSOFT IdpProvider = "MICROSOFT"
	IdpProviderSAML      IdpProvider = "SAML"
	IdpProviderOIDC      IdpProvider = "OIDC"
)

func (e *IdpProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdpProvider(s)
	case string:
		*e = IdpProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for IdpProvider: %T", src)
	}
	return nil
}

type NullIdpProvider struct {
	IdpProvider IdpProvider
	Valid       bool // Valid is true if IdpProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdpProvider) Scan(value interface{}) error {
	if value == nil {
		ns.IdpProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdpProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdpProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdpProvider), nil
}

type InvitationStatus string

const (
	InvitationStatusPENDING  InvitationStatus = "PENDING"
	InvitationStatusACCEPTED InvitationStatus = "ACCEPTED"
	InvitationStatusEXPIRED  InvitationStatus = "EXPIRED"
	InvitationStatusREVOKED  InvitationStatus = "REVOKED"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus
	Valid            bool // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type LoginStateKind string

const (
	LoginStateKindGOOGLE        LoginStateKind = "GOOGLE"
	LoginStateKindOIDC          LoginStateKind = "OIDC"
	LoginStateKindACCOUNTCHOICE LoginStateKind = "ACCOUNT_CHOICE"
)

func (e *LoginStateKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoginStateKind(s)
	case string:
		*e = LoginStateKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LoginStateKind: %T", src)
	}
	return nil
}

type NullLoginStateKind struct {
	LoginStateKind LoginStateKind
	Valid          bool // Valid is true if LoginStateKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoginStateKind) Scan(value interface{}) error {
	if value == nil {
		ns.LoginStateKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoginStateKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoginStateKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoginStateKind), nil
}

type SessionKind string

const (
	SessionKindCENTRAL SessionKind = "CENTRAL"
	SessionKindPRODUCT SessionKind = "PRODUCT"
)

func (e *SessionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionKind(s)
	case string:
		*e = SessionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionKind: %T", src)
	}
	return nil
}

type NullSessionKind struct {
	SessionKind SessionKind
	Valid       bool // Valid is true if SessionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionKind) Scan(value interface{}) error {
	if value == nil {
		ns.SessionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionKind), nil
}

type SessionRevokedReason string

const (
	SessionRevokedReasonLOGOUT        SessionRevokedReason = "LOGOUT"
	SessionRevokedReasonLOGOUTALL     SessionRevokedReason = "LOGOUT_ALL"
	SessionRevokedReasonREUSEDETECTED SessionRevokedReason = "REUSE_DETECTED"
	SessionRevokedReasonADMIN         SessionRevokedReason = "ADMIN"
	SessionRevokedReasonEXPIRED       SessionRevokedReason = "EXPIRED"
	SessionRevokedReasonPOLICY        SessionRevokedReason = "POLICY"
	SessionRevokedReasonACCESSLOST    SessionRevokedReason = "ACCESS_LOST"
	SessionRevokedReasonSUSPENDED     SessionRevokedReason = "SUSPENDED"
)

func (e *SessionRevokedReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionRevokedReason(s)
	case string:
		*e = SessionRevokedReason(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionRevokedReason: %T", src)
	}
	return nil
}

type NullSessionRevokedReason struct {
	SessionRevokedReason SessionRevokedReason
	Valid                bool // Valid is true if SessionRevokedReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionRevokedReason) Scan(value interface{}) error {
	if value == nil {
		ns.SessionRevokedReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionRevokedReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionRevokedReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionRevokedReason), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusTRIAL     SubscriptionStatus = "TRIAL"
	SubscriptionStatusACTIVE    SubscriptionStatus = "ACTIVE"
	SubscriptionStatusSUSPENDED SubscriptionStatus = "SUSPENDED"
	SubscriptionStatusCANCELLED SubscriptionStatus = "CANCELLED"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type TblApiClient struct {
	ID               string
	ClientID         string
	Name             string
	Description      pgtype.Text
	IsActive         bool
	CreatedByUserID  pgtype.Text
	CreatedByOwnerID pgtype.Text
	LastUsedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TblApiClientProduct struct {
	ApiClientID string
	ClientID    string
	ProductID   string
	CreatedAt   pgtype.Timestamptz
}

type TblApiClientScope struct {
	ApiClientID string
	ClientID    string
	Scope       string
	Kind        string
}

type TblApiClientSecret struct {
	ID               string
	ApiClientID      string
	ClientID         string
	SecretHash       string
	Prefix           string
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	CreatedByUserID  pgtype.Text
	CreatedByOwnerID pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type TblAuditLog struct {
	ID            string
	ClientID      string
	ActorUserID   pgtype.Text
	EventType     string
	EventMetadata json.RawMessage
	IpAddress     pgtype.Text
	UserAgent     pgtype.Text
	RequestID     pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type TblAuthorizationCode struct {
	ID                  string
	CodeHash            string
	ProductID           string
	UserID              string
	ClientID            string
	ParentFamilyID      string
	RedirectUri         string
	CodeChallenge       string
	CodeChallengeMethod string
	Nonce               pgtype.Text
	Scope               pgtype.Text
	ExpiresAt           pgtype.Timestamptz
	UsedAt              pgtype.Timestamptz
	IssuedFamilyID      pgtype.Text
	CreatedAt           pgtype.Timestamptz
}

type TblClient struct {
	ID                 string
	Name               string
	Domain             pgtype.Text
	DomainVerifiedAt   pgtype.Timestamptz
	SubscriptionStatus SubscriptionStatus
	MaxSeats           pgtype.Int4
	IsActive           bool
	IsPlatform         bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type TblClientProduct struct {
	ID        string
	ClientID  string
	ProductID string
	IsActive  bool
	SeatLimit pgtype.Int4
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type TblGroup struct {
	ID            string
	ClientID      string
	Name          string
	Description   pgtype.Text
	SystemKey     pgtype.Text
	LoginPolicyID pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TblGroupManager struct {
	GroupID            string
	ClientID           string
	UserID             string
	AppointedByUserID  pgtype.Text
	AppointedByOwnerID pgtype.Text
	AppointedAt        pgtype.Timestamptz
}

type TblGroupProductGrant struct {
	GroupID   string
	ClientID  string
	ProductID string
	RoleName  string
	GrantedBy pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type TblGroupScope struct {
	GroupID  string
	ClientID string
	Scope    string
	Kind     string
}

type TblInvitation struct {
	ID               string
	Email            string
	ClientID         string
	InvitedByUserID  pgtype.Text
	InvitedByOwnerID pgtype.Text
	TokenHash        string
	ExpiresAt        pgtype.Timestamptz
	Status           InvitationStatus
	AcceptedAt       pgtype.Timestamptz
	AcceptedByUserID pgtype.Text
	RevokedAt        pgtype.Timestamptz
	RevokedByUserID  pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TblInvitationGroup struct {
	InvitationID string
	ClientID     string
	GroupID      string
}

type TblLinkedIdentity struct {
	ID            string
	UserID        string
	ClientID      string
	Provider      IdpProvider
	ConnectionID  pgtype.Text
	ProviderID    string
	EmailVerified bool
	EmailAtLink   pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type TblLoginPolicy struct {
	ID              string
	ClientID        string
	Name            string
	AllowPassword   bool
	AllowGoogle     bool
	SsoConnectionID pgtype.Text
	Priority        int32
	IsDefault       bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type TblLoginState struct {
	StateHash        string
	Kind             LoginStateKind
	ConnectionID     pgtype.Text
	Nonce            pgtype.Text
	CodeVerifier     pgtype.Text
	ReturnTo         pgtype.Text
	CandidateUserIds []string
	AuthMethod       NullIdpProvider
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type TblPasswordResetToken struct {
	ID        string
	UserID    string
	ClientID  string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedBy string
	CreatedAt pgtype.Timestamptz
}

type TblPlatformOwner struct {
	UserID     string
	ClientID   string
	IsPlatform bool
	CreatedAt  pgtype.Timestamptz
}

type TblProduct struct {
	ID                string
	Key               string
	Name              string
	Description       pgtype.Text
	BaseUrl           pgtype.Text
	InitiateLoginUri  pgtype.Text
	ClientSecretHash  pgtype.Text
	SecretRotatedAt   pgtype.Timestamptz
	IsActive          bool
	AcceptsApiClients bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type TblProductPermission struct {
	ID         string
	UserID     string
	ClientID   string
	ProductID  string
	RoleName   string
	GrantedBy  pgtype.Text
	ValidFrom  pgtype.Timestamptz
	ValidUntil pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type TblProductRedirectUri struct {
	ProductID   string
	RedirectUri string
	CreatedAt   pgtype.Timestamptz
}

type TblProductRole struct {
	ProductID   string
	RoleName    string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type TblRateLimitCounter struct {
	BucketKey string
	Hits      int32
	ResetAt   pgtype.Timestamptz
}

type TblSchemaMigration struct {
	Version    string
	Checksum   string
	AppliedAt  pgtype.Timestamptz
	AppliedBy  string
	DurationMs pgtype.Int4
}

type TblScope struct {
	Scope       string
	Kind        string
	Feature     string
	Level       string
	Description string
	SortOrder   int32
}

type TblSessionFamily struct {
	ID                string
	UserID            string
	ClientID          string
	Kind              SessionKind
	ProductID         pgtype.Text
	ParentFamilyID    pgtype.Text
	AuthMethod        IdpProvider
	AuthConnectionID  pgtype.Text
	AuthenticatedAt   pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	RevokedReason     NullSessionRevokedReason
	CreatedAt         pgtype.Timestamptz
}

type TblSsoConnection struct {
	ID                     string
	ClientID               string
	Name                   string
	Issuer                 string
	OidcClientID           string
	ClientSecretCiphertext []byte
	SecretKeyID            pgtype.Text
	Scopes                 string
	TrustUnverifiedEmail   bool
	IsActive               bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type TblSsoConnectionDomain struct {
	Domain       string
	ConnectionID string
	ClientID     string
}

type TblUser struct {
	ID                 string
	ClientID           string
	Email              string
	PasswordHash       pgtype.Text
	AccountType        AccountType
	IsActive           bool
	PermissionsVersion int32
	AdminVersion       int32
	LoginPolicyID      pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type TblUserGroup struct {
	UserID     string
	GroupID    string
	ClientID   string
	AssignedAt pgtype.Timestamptz
	AssignedBy pgtype.Text
}

type TblUserScope struct {
	UserID           string
	ClientID         string
	Scope            string
	Kind             string
	GrantedByUserID  pgtype.Text
	GrantedByOwnerID pgtype.Text
	GrantedAt        pgtype.Timestamptz
}

type TblUserSession struct {
	ID               string
	UserID           string
	ClientID         string
	SessionUuid      string
	FamilyID         string
	Generation       int32
	RefreshTokenHash string
	PrevTokenHash    pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevokedReason    NullSessionRevokedReason
	IpAddress        pgtype.Text
	DeviceLabel      pgtype.Text
	UserAgent        pgtype.Text
	LastSeenAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	ReplacedByID     pgtype.Text
}

type VwApiclientgrant struct {
	ApiClientID string
	ClientID    string
	ProductID   string
	ProductKey  string
	Usable      bool
	Scopes      []string
}

type VwApiclientsecret struct {
	ID               string
	ApiClientID      string
	ClientID         string
	Prefix           string
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	CreatedByUserID  pgtype.Text
	CreatedByOwnerID pgtype.Text
	CreatedAt        pgtype.Timestamptz
	IsLive           bool
}

type VwApiclientsummary struct {
	ID               string
	ClientID         string
	CompanyName      string
	Name             string
	Description      pgtype.Text
	IsActive         bool
	CreatedByUserID  pgtype.Text
	CreatedByOwnerID pgtype.Text
	LastUsedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Scopes           interface{}
	Products         interface{}
	LiveSecrets      int32
}

type VwClientproductdetail struct {
	ID                       string
	ClientID                 string
	ProductID                string
	IsActive                 bool
	SeatLimit                pgtype.Int4
	StartsAt                 pgtype.Timestamptz
	EndsAt                   pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	ProductKey               string
	ProductName              string
	ProductDescription       pgtype.Text
	ProductBaseUrl           pgtype.Text
	ProductIsActive          bool
	ProductAcceptsApiClients bool
}

type VwCompanylistitem struct {
	ID                 string
	Name               string
	Domain             pgtype.Text
	DomainVerifiedAt   pgtype.Timestamptz
	SubscriptionStatus SubscriptionStatus
	MaxSeats           pgtype.Int4
	IsActive           bool
	IsPlatform         bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	UserCount          int64
}

type VwDomainloginhint struct {
	Domain        string
	ClientID      string
	ConnectionID  pgtype.Text
	AllowPassword bool
	AllowGoogle   bool
}

type VwEffectiveproductrole struct {
	UserID      string
	ClientID    string
	ProductID   string
	ProductKey  string
	ProductName string
	RoleName    string
	Source      string
	GroupID     pgtype.Text
}

type VwEffectivescope struct {
	UserID    string
	ClientID  string
	Scope     string
	Source    string
	GroupID   pgtype.Text
	GroupName pgtype.Text
}

type VwGroupdetailrow struct {
	ID            string
	ClientID      string
	Name          string
	Description   pgtype.Text
	SystemKey     pgtype.Text
	LoginPolicyID pgtype.Text
	CreatedAt     pgtype.Timestamptz
	Scopes        interface{}
	ProductGrants interface{}
	UserID        pgtype.Text
	UserEmail     pgtype.Text
	AssignedAt    pgtype.Timestamptz
}

type VwGrouplistitem struct {
	ID            string
	ClientID      string
	Name          string
	Description   pgtype.Text
	SystemKey     pgtype.Text
	LoginPolicyID pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Scopes        interface{}
	ProductGrants interface{}
	MemberCount   int64
}

type VwGroupmanager struct {
	GroupID          string
	ClientID         string
	UserID           string
	Email            string
	AppointedAt      pgtype.Timestamptz
	AppointedByEmail string
	AppointedByOwner bool
}

type VwInvitationgroup struct {
	InvitationID string
	ClientID     string
	GroupID      string
	GroupName    string
}

type VwInvitationlistitem struct {
	ID        string
	ClientID  string
	Email     string
	Status    InvitationStatus
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type VwLinkedidentityowner struct {
	Provider     IdpProvider
	ConnectionID pgtype.Text
	ProviderID   string
	UserID       string
	ClientID     string
	Email        string
	AccountType  AccountType
	IsActive     bool
}

type VwOauthclientcredential struct {
	Kind          string
	OauthClientID string
	ProductKey    string
	CompanyID     string
	SecretID      string
	SecretHash    pgtype.Text
	IsActive      bool
}

type VwPendinginvitation struct {
	ID               string
	Email            string
	ClientID         string
	InvitedByUserID  pgtype.Text
	InvitedByOwnerID pgtype.Text
	TokenHash        string
	ExpiresAt        pgtype.Timestamptz
	ClientName       string
}

type VwProductclient struct {
	ID                string
	Key               string
	Name              string
	Description       pgtype.Text
	BaseUrl           pgtype.Text
	InitiateLoginUri  pgtype.Text
	IsActive          bool
	AcceptsApiClients bool
	HasSecret         bool
	SecretRotatedAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type VwProductclientcredential struct {
	ID               string
	Key              string
	IsActive         bool
	ClientSecretHash pgtype.Text
}

type VwScopereach struct {
	UserID   string
	ClientID string
	Scope    string
	Via      string
	GroupID  pgtype.Text
}

type VwSessionfamilygate struct {
	FamilyID           string
	UserID             string
	ClientID           string
	Kind               SessionKind
	ProductID          pgtype.Text
	ParentFamilyID     pgtype.Text
	AuthMethod         IdpProvider
	AuthConnectionID   pgtype.Text
	AuthenticatedAt    pgtype.Timestamptz
	AbsoluteExpiresAt  pgtype.Timestamptz
	FamilyAlive        bool
	ParentAlive        bool
	UserActive         bool
	ClientActive       bool
	Email              string
	PermissionsVersion int32
	IsTenantAdmin      bool
	IsPlatformOwner    bool
	HasAccess          bool
	AdminVersion       int32
	Scopes             []string
}

type VwSessionfamilysummary struct {
	ID              string
	ClientID        string
	Kind            SessionKind
	ProductKey      pgtype.Text
	AuthMethod      IdpProvider
	AuthenticatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	DeviceLabel     string
	IpAddress       string
	LastSeenAt      pgtype.Timestamptz
	Email           string
}

type VwSessionowner struct {
	ID               string
	FamilyID         string
	UserID           string
	ClientID         string
	RevokedAt        pgtype.Timestamptz
	RefreshTokenHash string
}

type VwSsoconnectionruntime struct {
	ID                     string
	ClientID               string
	Name                   string
	Issuer                 string
	OidcClientID           string
	ClientSecretCiphertext []byte
	SecretKeyID            pgtype.Text
	Scopes                 string
	TrustUnverifiedEmail   bool
	IsActive               bool
	Domains                []string
}

type VwSsoconnectionsummary struct {
	ID                   string
	ClientID             string
	Name                 string
	Issuer               string
	OidcClientID         string
	Scopes               string
	TrustUnverifiedEmail bool
	IsActive             bool
	HasSecret            bool
	Domains              []string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type VwUserapp struct {
	UserID             string
	ClientID           string
	ProductID          string
	ProductKey         string
	ProductName        string
	ProductDescription pgtype.Text
	BaseUrl            pgtype.Text
	InitiateLoginUri   pgtype.Text
	Roles              []string
}

type VwUsercredential struct {
	ID           string
	ClientID     string
	Email        string
	PasswordHash pgtype.Text
	AccountType  AccountType
	CreatedAt    pgtype.Timestamptz
}

type VwUsergroupmembership struct {
	UserID     string
	ClientID   string
	GroupID    string
	GroupName  string
	SystemKey  pgtype.Text
	AssignedAt pgtype.Timestamptz
}

type VwUseridentity struct {
	ID                 string
	ClientID           string
	Email              string
	PermissionsVersion int32
}

type VwUserlistitem struct {
	ID                 string
	ClientID           string
	Email              string
	AccountType        AccountType
	IsActive           bool
	PermissionsVersion int32
	LoginPolicyID      pgtype.Text
	IsAdmin            bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	IsOwner            bool
}

type VwUserloginpolicy struct {
	UserID          string
	ClientID        string
	PolicyID        string
	PolicyName      string
	AllowPassword   bool
	AllowGoogle     bool
	SsoConnectionID pgtype.Text
	Source          string
}

type VwUserproductrole struct {
	UserID      string
	ClientID    string
	ProductID   string
	ProductKey  string
	ProductName string
	RoleName    string
	ValidUntil  pgtype.Timestamptz
}

type VwUsertenantscoped struct {
	ID                 string
	ClientID           string
	Email              string
	AccountType        AccountType
	IsActive           bool
	PermissionsVersion int32
	LoginPolicyID      pgtype.Text
	IsAdmin            bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	IsOwner            bool
}

type VwValidresettoken struct {
	ID        string
	UserID    string
	ClientID  string
	TokenHash string
	Email     string
	IsActive  bool
	DeletedAt pgtype.Timestamptz
}
