// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAuthorizationCode = `-- name: ClaimAuthorizationCode :one
SELECT id, code_hash, product_id, user_id, client_id, parent_family_id, redirect_uri, code_challenge, code_challenge_method, nonce, scope, expires_at, used_at, issued_family_id, created_at FROM stp_ClaimAuthorizationCode($1)
`

func (q *Queries) ClaimAuthorizationCode(ctx context.Context, pCodehash string) (TblAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, claimAuthorizationCode, pCodehash)
	var i TblAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ProductID,
		&i.UserID,
		&i.ClientID,
		&i.ParentFamilyID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Nonce,
		&i.Scope,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IssuedFamilyID,
		&i.CreatedAt,
	)
	return i, err
}

const cleanupExpiredAuthCodes = `-- name: CleanupExpiredAuthCodes :one
SELECT stp_CleanupExpiredAuthCodes()
`

func (q *Queries) CleanupExpiredAuthCodes(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, cleanupExpiredAuthCodes)
	var stp_cleanupexpiredauthcodes int32
	err := row.Scan(&stp_cleanupexpiredauthcodes)
	return stp_cleanupexpiredauthcodes, err
}

const cleanupLoginStates = `-- name: CleanupLoginStates :one
SELECT stp_CleanupLoginStates()
`

func (q *Queries) CleanupLoginStates(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, cleanupLoginStates)
	var stp_cleanuploginstates int32
	err := row.Scan(&stp_cleanuploginstates)
	return stp_cleanuploginstates, err
}

const clientIdByVerifiedDomain = `-- name: ClientIdByVerifiedDomain :one
SELECT id FROM (SELECT udf_ClientIdByVerifiedDomain($1) AS id) t WHERE id IS NOT NULL
`

// Filtered so an unknown domain yields zero rows (see entitlements.sql).
func (q *Queries) ClientIdByVerifiedDomain(ctx context.Context, pDomain string) (string, error) {
	row := q.db.QueryRow(ctx, clientIdByVerifiedDomain, pDomain)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one

SELECT id, code_hash, product_id, user_id, client_id, parent_family_id, redirect_uri, code_challenge, code_challenge_method, nonce, scope, expires_at, used_at, issued_family_id, created_at FROM stp_CreateAuthorizationCode(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateAuthorizationCodeParams struct {
	CodeHash            string
	ProductID           string
	UserID              string
	ClientID            string
	ParentFamilyID      string
	RedirectUri         string
	CodeChallenge       string
	CodeChallengeMethod string
	Nonce               pgtype.Text
	Scope               pgtype.Text
	ExpiresAt           pgtype.Timestamptz
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: authorization codes, federated identities and sign-in states
//
// The single-use guarantees are enforced inside stp_ClaimAuthorizationCode and
// stp_TakeLoginState as one atomic statement each, so no caller can reintroduce
// a check-then-act race.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (TblAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.CodeHash,
		arg.ProductID,
		arg.UserID,
		arg.ClientID,
		arg.ParentFamilyID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Nonce,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i TblAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ProductID,
		&i.UserID,
		&i.ClientID,
		&i.ParentFamilyID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Nonce,
		&i.Scope,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IssuedFamilyID,
		&i.CreatedAt,
	)
	return i, err
}

const createLinkedIdentity = `-- name: CreateLinkedIdentity :one
SELECT id, user_id, client_id, provider, connection_id, provider_id, email_verified, email_at_link, created_at FROM stp_CreateLinkedIdentity(
    $1,
    $2,
    $3::"IdpProvider",
    $4,
    $5,
    $6,
    $7
)
`

type CreateLinkedIdentityParams struct {
	UserID        string
	ClientID      string
	Provider      IdpProvider
	ConnectionID  pgtype.Text
	ProviderID    string
	EmailVerified bool
	EmailAtLink   pgtype.Text
}

func (q *Queries) CreateLinkedIdentity(ctx context.Context, arg CreateLinkedIdentityParams) (TblLinkedIdentity, error) {
	row := q.db.QueryRow(ctx, createLinkedIdentity,
		arg.UserID,
		arg.ClientID,
		arg.Provider,
		arg.ConnectionID,
		arg.ProviderID,
		arg.EmailVerified,
		arg.EmailAtLink,
	)
	var i TblLinkedIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Provider,
		&i.ConnectionID,
		&i.ProviderID,
		&i.EmailVerified,
		&i.EmailAtLink,
		&i.CreatedAt,
	)
	return i, err
}

const createLoginState = `-- name: CreateLoginState :exec
CALL stp_CreateLoginState(
    $1,
    $2::"LoginStateKind",
    $3,
    $4,
    $5,
    $6,
    $7::text[],
    $8::"IdpProvider",
    $9
)
`

type CreateLoginStateParams struct {
	StateHash        string
	Kind             LoginStateKind
	ConnectionID     pgtype.Text
	Nonce            pgtype.Text
	CodeVerifier     pgtype.Text
	ReturnTo         pgtype.Text
	CandidateUserIds []string
	AuthMethod       NullIdpProvider
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateLoginState(ctx context.Context, arg CreateLoginStateParams) error {
	_, err := q.db.Exec(ctx, createLoginState,
		arg.StateHash,
		arg.Kind,
		arg.ConnectionID,
		arg.Nonce,
		arg.CodeVerifier,
		arg.ReturnTo,
		arg.CandidateUserIds,
		arg.AuthMethod,
		arg.ExpiresAt,
	)
	return err
}

const deleteLinkedIdentity = `-- name: DeleteLinkedIdentity :one
SELECT stp_DeleteLinkedIdentity(
    $1,
    $2,
    $3::"IdpProvider",
    $4
)
`

type DeleteLinkedIdentityParams struct {
	UserID       string
	ClientID     string
	Provider     IdpProvider
	ConnectionID pgtype.Text
}

func (q *Queries) DeleteLinkedIdentity(ctx context.Context, arg DeleteLinkedIdentityParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteLinkedIdentity,
		arg.UserID,
		arg.ClientID,
		arg.Provider,
		arg.ConnectionID,
	)
	var stp_deletelinkedidentity int32
	err := row.Scan(&stp_deletelinkedidentity)
	return stp_deletelinkedidentity, err
}

const getAuthorizationCodeByHash = `-- name: GetAuthorizationCodeByHash :one
SELECT id, code_hash, product_id, user_id, client_id, parent_family_id, redirect_uri, code_challenge, code_challenge_method, nonce, scope, expires_at, used_at, issued_family_id, created_at FROM udf_GetAuthorizationCodeByHash($1)
`

func (q *Queries) GetAuthorizationCodeByHash(ctx context.Context, pCodehash string) (TblAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCodeByHash, pCodehash)
	var i TblAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ProductID,
		&i.UserID,
		&i.ClientID,
		&i.ParentFamilyID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Nonce,
		&i.Scope,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IssuedFamilyID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkedIdentityByConnection = `-- name: GetLinkedIdentityByConnection :one
SELECT provider, connection_id, provider_id, user_id, client_id, email, account_type, is_active FROM udf_GetLinkedIdentityByConnection($1, $2)
`

type GetLinkedIdentityByConnectionParams struct {
	PConnectionid string
	PSubject      string
}

func (q *Queries) GetLinkedIdentityByConnection(ctx context.Context, arg GetLinkedIdentityByConnectionParams) (VwLinkedidentityowner, error) {
	row := q.db.QueryRow(ctx, getLinkedIdentityByConnection, arg.PConnectionid, arg.PSubject)
	var i VwLinkedidentityowner
	err := row.Scan(
		&i.Provider,
		&i.ConnectionID,
		&i.ProviderID,
		&i.UserID,
		&i.ClientID,
		&i.Email,
		&i.AccountType,
		&i.IsActive,
	)
	return i, err
}

const getLoginState = `-- name: GetLoginState :one
SELECT state_hash, kind, connection_id, nonce, code_verifier, return_to, candidate_user_ids, auth_method, expires_at, created_at FROM udf_GetLoginState(
    $1,
    $2::"LoginStateKind"
)
`

type GetLoginStateParams struct {
	StateHash string
	Kind      LoginStateKind
}

func (q *Queries) GetLoginState(ctx context.Context, arg GetLoginStateParams) (TblLoginState, error) {
	row := q.db.QueryRow(ctx, getLoginState, arg.StateHash, arg.Kind)
	var i TblLoginState
	err := row.Scan(
		&i.StateHash,
		&i.Kind,
		&i.ConnectionID,
		&i.Nonce,
		&i.CodeVerifier,
		&i.ReturnTo,
		&i.CandidateUserIds,
		&i.AuthMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGoogleLinks = `-- name: ListGoogleLinks :many
SELECT provider, connection_id, provider_id, user_id, client_id, email, account_type, is_active FROM udf_ListGoogleLinks($1)
`

func (q *Queries) ListGoogleLinks(ctx context.Context, pSubject string) ([]VwLinkedidentityowner, error) {
	rows, err := q.db.Query(ctx, listGoogleLinks, pSubject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwLinkedidentityowner{}
	for rows.Next() {
		var i VwLinkedidentityowner
		if err := rows.Scan(
			&i.Provider,
			&i.ConnectionID,
			&i.ProviderID,
			&i.UserID,
			&i.ClientID,
			&i.Email,
			&i.AccountType,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCodeIssuedFamily = `-- name: SetCodeIssuedFamily :exec
CALL stp_SetCodeIssuedFamily($1, $2)
`

type SetCodeIssuedFamilyParams struct {
	PCodeid   string
	PFamilyid string
}

func (q *Queries) SetCodeIssuedFamily(ctx context.Context, arg SetCodeIssuedFamilyParams) error {
	_, err := q.db.Exec(ctx, setCodeIssuedFamily, arg.PCodeid, arg.PFamilyid)
	return err
}

const takeLoginState = `-- name: TakeLoginState :one
SELECT state_hash, kind, connection_id, nonce, code_verifier, return_to, candidate_user_ids, auth_method, expires_at, created_at FROM stp_TakeLoginState(
    $1,
    $2::"LoginStateKind"
)
`

type TakeLoginStateParams struct {
	StateHash string
	Kind      LoginStateKind
}

func (q *Queries) TakeLoginState(ctx context.Context, arg TakeLoginStateParams) (TblLoginState, error) {
	row := q.db.QueryRow(ctx, takeLoginState, arg.StateHash, arg.Kind)
	var i TblLoginState
	err := row.Scan(
		&i.StateHash,
		&i.Kind,
		&i.ConnectionID,
		&i.Nonce,
		&i.CodeVerifier,
		&i.ReturnTo,
		&i.CandidateUserIds,
		&i.AuthMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
