// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginPolicy = `-- name: CreateLoginPolicy :one
SELECT id, client_id, name, allow_password, allow_google, sso_connection_id, priority, is_default, created_at, updated_at FROM stp_CreateLoginPolicy(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateLoginPolicyParams struct {
	ClientID        string
	Name            string
	AllowPassword   bool
	AllowGoogle     bool
	SsoConnectionID pgtype.Text
	Priority        int32
}

func (q *Queries) CreateLoginPolicy(ctx context.Context, arg CreateLoginPolicyParams) (TblLoginPolicy, error) {
	row := q.db.QueryRow(ctx, createLoginPolicy,
		arg.ClientID,
		arg.Name,
		arg.AllowPassword,
		arg.AllowGoogle,
		arg.SsoConnectionID,
		arg.Priority,
	)
	var i TblLoginPolicy
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.AllowPassword,
		&i.AllowGoogle,
		&i.SsoConnectionID,
		&i.Priority,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLoginPolicy = `-- name: DeleteLoginPolicy :one
SELECT stp_DeleteLoginPolicy($1, $2)
`

type DeleteLoginPolicyParams struct {
	PPolicyid string
	PClientid string
}

func (q *Queries) DeleteLoginPolicy(ctx context.Context, arg DeleteLoginPolicyParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteLoginPolicy, arg.PPolicyid, arg.PClientid)
	var stp_deleteloginpolicy int32
	err := row.Scan(&stp_deleteloginpolicy)
	return stp_deleteloginpolicy, err
}

const getDomainLoginHint = `-- name: GetDomainLoginHint :one
SELECT domain, client_id, connection_id, allow_password, allow_google FROM udf_GetDomainLoginHint($1)
`

func (q *Queries) GetDomainLoginHint(ctx context.Context, pDomain string) (VwDomainloginhint, error) {
	row := q.db.QueryRow(ctx, getDomainLoginHint, pDomain)
	var i VwDomainloginhint
	err := row.Scan(
		&i.Domain,
		&i.ClientID,
		&i.ConnectionID,
		&i.AllowPassword,
		&i.AllowGoogle,
	)
	return i, err
}

const getLoginPolicy = `-- name: GetLoginPolicy :one
SELECT id, client_id, name, allow_password, allow_google, sso_connection_id, priority, is_default, created_at, updated_at FROM udf_GetLoginPolicy($1, $2)
`

type GetLoginPolicyParams struct {
	PPolicyid string
	PClientid string
}

func (q *Queries) GetLoginPolicy(ctx context.Context, arg GetLoginPolicyParams) (TblLoginPolicy, error) {
	row := q.db.QueryRow(ctx, getLoginPolicy, arg.PPolicyid, arg.PClientid)
	var i TblLoginPolicy
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.AllowPassword,
		&i.AllowGoogle,
		&i.SsoConnectionID,
		&i.Priority,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLoginPolicies = `-- name: ListLoginPolicies :many

SELECT id, client_id, name, allow_password, allow_google, sso_connection_id, priority, is_default, created_at, updated_at FROM udf_ListLoginPolicies($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: login policies and login discovery
//
// Which policy applies to a user is resolved in vw_UserLoginPolicy (users.sql);
// these are the Owner's management entry points and the domain-only discovery
// hint the login page uses.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) ListLoginPolicies(ctx context.Context, pClientid string) ([]TblLoginPolicy, error) {
	rows, err := q.db.Query(ctx, listLoginPolicies, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblLoginPolicy{}
	for rows.Next() {
		var i TblLoginPolicy
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.AllowPassword,
			&i.AllowGoogle,
			&i.SsoConnectionID,
			&i.Priority,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultLoginPolicy = `-- name: SetDefaultLoginPolicy :one
SELECT stp_SetDefaultLoginPolicy($1, $2)
`

type SetDefaultLoginPolicyParams struct {
	PPolicyid string
	PClientid string
}

func (q *Queries) SetDefaultLoginPolicy(ctx context.Context, arg SetDefaultLoginPolicyParams) (int32, error) {
	row := q.db.QueryRow(ctx, setDefaultLoginPolicy, arg.PPolicyid, arg.PClientid)
	var stp_setdefaultloginpolicy int32
	err := row.Scan(&stp_setdefaultloginpolicy)
	return stp_setdefaultloginpolicy, err
}

const updateLoginPolicy = `-- name: UpdateLoginPolicy :one
SELECT id, client_id, name, allow_password, allow_google, sso_connection_id, priority, is_default, created_at, updated_at FROM stp_UpdateLoginPolicy(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type UpdateLoginPolicyParams struct {
	PolicyID        string
	ClientID        string
	Name            string
	AllowPassword   bool
	AllowGoogle     bool
	SsoConnectionID pgtype.Text
	Priority        int32
}

func (q *Queries) UpdateLoginPolicy(ctx context.Context, arg UpdateLoginPolicyParams) (TblLoginPolicy, error) {
	row := q.db.QueryRow(ctx, updateLoginPolicy,
		arg.PolicyID,
		arg.ClientID,
		arg.Name,
		arg.AllowPassword,
		arg.AllowGoogle,
		arg.SsoConnectionID,
		arg.Priority,
	)
	var i TblLoginPolicy
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.AllowPassword,
		&i.AllowGoogle,
		&i.SsoConnectionID,
		&i.Priority,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
