// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveEmailExists(ctx context.Context, arg ActiveEmailExistsParams) (bool, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: subscriptions and direct product-role grants
	// ─────────────────────────────────────────────────────────────────────────────
	// Filtered so a NULL (no subscription) yields ZERO ROWS rather than one NULL
	// row: a scalar function always returns a row, and the caller distinguishes
	// "not found" by pgx.ErrNoRows.
	ActiveSubscriptionId(ctx context.Context, arg ActiveSubscriptionIdParams) (string, error)
	AddGroupManager(ctx context.Context, arg AddGroupManagerParams) (int32, error)
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	BumpPermissionsVersion(ctx context.Context, arg BumpPermissionsVersionParams) error
	ClaimAuthorizationCode(ctx context.Context, pCodehash string) (TblAuthorizationCode, error)
	ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (TblInvitation, error)
	CleanupExpiredAuthCodes(ctx context.Context) (int32, error)
	CleanupLoginStates(ctx context.Context) (int32, error)
	CleanupRateLimitCounters(ctx context.Context) (int32, error)
	// Filtered so an unknown domain yields zero rows (see entitlements.sql).
	ClientIdByVerifiedDomain(ctx context.Context, pDomain string) (string, error)
	// Filtered so an unknown tenant yields zero rows (see entitlements.sql).
	ClientNameById(ctx context.Context, pClientid string) (string, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: API clients — applications' identities, where their credential
	// may be used (CLIENT scopes), the products they may get a token for, and their
	// secrets
	//
	// Every read and write is tenant-scoped by (id, client_id) inside the routine,
	// so a foreign id finds and changes nothing. Secrets are stored as hashes only,
	// and no read here returns one.
	// ─────────────────────────────────────────────────────────────────────────────
	CreateApiClient(ctx context.Context, arg CreateApiClientParams) (TblApiClient, error)
	CreateApiClientSecret(ctx context.Context, arg CreateApiClientSecretParams) (VwApiclientsecret, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: authorization codes, federated identities and sign-in states
	//
	// The single-use guarantees are enforced inside stp_ClaimAuthorizationCode and
	// stp_TakeLoginState as one atomic statement each, so no caller can reintroduce
	// a check-then-act race.
	// ─────────────────────────────────────────────────────────────────────────────
	CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (TblAuthorizationCode, error)
	CreateCentralFamily(ctx context.Context, arg CreateCentralFamilyParams) (TblUserSession, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (TblClient, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (TblGroup, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TblInvitation, error)
	CreateInvitationGroup(ctx context.Context, arg CreateInvitationGroupParams) error
	CreateLinkedIdentity(ctx context.Context, arg CreateLinkedIdentityParams) (TblLinkedIdentity, error)
	CreateLoginPolicy(ctx context.Context, arg CreateLoginPolicyParams) (TblLoginPolicy, error)
	CreateLoginState(ctx context.Context, arg CreateLoginStateParams) error
	// Provisioning only: fails under the application role by design.
	CreatePlatformOwner(ctx context.Context, arg CreatePlatformOwnerParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (TblProduct, error)
	CreateProductFamily(ctx context.Context, arg CreateProductFamilyParams) (TblUserSession, error)
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (TblPasswordResetToken, error)
	CreateSsoConnection(ctx context.Context, arg CreateSsoConnectionParams) (TblSsoConnection, error)
	CreateSuccessorSession(ctx context.Context, arg CreateSuccessorSessionParams) (TblUserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (TblUser, error)
	DeleteApiClient(ctx context.Context, arg DeleteApiClientParams) (int32, error)
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int32, error)
	DeleteLinkedIdentity(ctx context.Context, arg DeleteLinkedIdentityParams) (int32, error)
	DeleteLoginPolicy(ctx context.Context, arg DeleteLoginPolicyParams) (int32, error)
	DeleteProductPermission(ctx context.Context, arg DeleteProductPermissionParams) (int32, error)
	DeleteUnusedResetTokens(ctx context.Context, pUserid string) error
	ExpireInvitations(ctx context.Context, pBatchsize int32) error
	ExpireSessions(ctx context.Context, pBatchsize int32) error
	GetApiClient(ctx context.Context, arg GetApiClientParams) (VwApiclientsummary, error)
	GetApiClientGrant(ctx context.Context, arg GetApiClientGrantParams) (VwApiclientgrant, error)
	GetAuthorizationCodeByHash(ctx context.Context, pCodehash string) (TblAuthorizationCode, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: tenants and the product catalogue
	// ─────────────────────────────────────────────────────────────────────────────
	GetClientById(ctx context.Context, pClientid string) (TblClient, error)
	GetDomainLoginHint(ctx context.Context, pDomain string) (VwDomainloginhint, error)
	GetGraceSuccessor(ctx context.Context, arg GetGraceSuccessorParams) (TblUserSession, error)
	GetGroupDetail(ctx context.Context, arg GetGroupDetailParams) ([]VwGroupdetailrow, error)
	GetGroupTenantScoped(ctx context.Context, arg GetGroupTenantScopedParams) (TblGroup, error)
	GetInvitationLoginPolicy(ctx context.Context, arg GetInvitationLoginPolicyParams) (TblLoginPolicy, error)
	GetLinkedIdentityByConnection(ctx context.Context, arg GetLinkedIdentityByConnectionParams) (VwLinkedidentityowner, error)
	GetLoginPolicy(ctx context.Context, arg GetLoginPolicyParams) (TblLoginPolicy, error)
	GetLoginState(ctx context.Context, arg GetLoginStateParams) (TblLoginState, error)
	GetOAuthClientCredentials(ctx context.Context, pOauthclientid string) ([]VwOauthclientcredential, error)
	GetOAuthLinkableUser(ctx context.Context, arg GetOAuthLinkableUserParams) (VwUsertenantscoped, error)
	GetPendingInvitation(ctx context.Context, pTokenhash string) (VwPendinginvitation, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: invitations
	//
	// The redeemable-invitation predicates (pending, unexpired, active tenant) live
	// in vw_PendingInvitation, so every lookup below inherits them and no caller can
	// accidentally honour a dead invitation.
	// ─────────────────────────────────────────────────────────────────────────────
	GetPendingInviteByEmail(ctx context.Context, arg GetPendingInviteByEmailParams) (VwPendinginvitation, error)
	GetProductById(ctx context.Context, arg GetProductByIdParams) (TblProduct, error)
	GetProductClient(ctx context.Context, pProductid string) (VwProductclient, error)
	GetProductClientCredential(ctx context.Context, pProductid string) (VwProductclientcredential, error)
	GetProductPermission(ctx context.Context, arg GetProductPermissionParams) (VwUserproductrole, error)
	GetSessionById(ctx context.Context, pSessionid string) (TblUserSession, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: sessions (logins and refresh-token rotation)
	//
	// A login is a family (tbl_session_families); each refresh appends a generation
	// (tbl_user_sessions). The rotation sequence is orchestrated by the API inside
	// ONE transaction, but every individual statement is a database object. In
	// particular the lock is taken by udf_GetSessionByRefreshHashForUpdate, so the
	// FOR UPDATE that serialises concurrent rotations lives in the database.
	// ─────────────────────────────────────────────────────────────────────────────
	GetSessionByRefreshHashForUpdate(ctx context.Context, pTokenhash string) (TblUserSession, error)
	GetSessionFamilyGate(ctx context.Context, pFamilyid string) (VwSessionfamilygate, error)
	GetSessionForLogout(ctx context.Context, pTokenhash string) (VwSessionowner, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: tenants' own OIDC identity providers
	//
	// The client secret enters and leaves only as ciphertext; the key that decrypts
	// it is held by the API, never by the database.
	// ─────────────────────────────────────────────────────────────────────────────
	GetSsoConnection(ctx context.Context, pConnectionid string) (VwSsoconnectionruntime, error)
	// Filtered so a missing system group yields zero rows (see entitlements.sql).
	GetSystemGroupId(ctx context.Context, arg GetSystemGroupIdParams) (string, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: users
	//
	// Every statement in this folder is a CALL of a procedure or a SELECT from a
	// function. Nothing here reads or writes a table directly, so all query logic —
	// predicates, projections, tenant scoping — lives in the database objects under
	// db/Tables, db/Views and db/Programmability and can be reviewed there in one
	// place.
	// ─────────────────────────────────────────────────────────────────────────────
	GetUserById(ctx context.Context, pUserid string) (TblUser, error)
	GetUserForSsoLink(ctx context.Context, arg GetUserForSsoLinkParams) (VwUsertenantscoped, error)
	GetUserIdentityForToken(ctx context.Context, pUserid string) (VwUseridentity, error)
	GetUserLoginPolicy(ctx context.Context, arg GetUserLoginPolicyParams) (VwUserloginpolicy, error)
	GetUserTenantScoped(ctx context.Context, arg GetUserTenantScopedParams) (VwUsertenantscoped, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: password reset
	//
	// vw_ValidResetToken carries the unused and unexpired predicates and surfaces the
	// owner's state, so the caller cannot honour a spent link or revive a disabled
	// account.
	// ─────────────────────────────────────────────────────────────────────────────
	GetValidResetToken(ctx context.Context, pTokenhash string) (VwValidresettoken, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: readiness probe
	// ─────────────────────────────────────────────────────────────────────────────
	HealthCheck(ctx context.Context) (int32, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: audit trail
	//
	// Insert only. There is deliberately no update or delete entry point, so the
	// application has no way to rewrite history even if it tried.
	// ─────────────────────────────────────────────────────────────────────────────
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	IsApiClientSecretLive(ctx context.Context, arg IsApiClientSecretLiveParams) (bool, error)
	IsGroupManager(ctx context.Context, arg IsGroupManagerParams) (bool, error)
	IsRedirectUriRegistered(ctx context.Context, arg IsRedirectUriRegisteredParams) (bool, error)
	ListActiveProducts(ctx context.Context) ([]TblProduct, error)
	ListAllApiClients(ctx context.Context) ([]VwApiclientsummary, error)
	ListApiClientProductChoices(ctx context.Context, pClientid string) ([]VwClientproductdetail, error)
	ListApiClientSecrets(ctx context.Context, arg ListApiClientSecretsParams) ([]VwApiclientsecret, error)
	ListApiClients(ctx context.Context, pClientid string) ([]VwApiclientsummary, error)
	ListClientProducts(ctx context.Context, pClientid string) ([]VwClientproductdetail, error)
	ListCompanies(ctx context.Context) ([]VwCompanylistitem, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: effective product access
	//
	// vw_EffectiveProductRole is the single definition of "may use this product":
	// direct grants plus group grants, only for live users, active tenants and
	// products, and live subscriptions.
	// ─────────────────────────────────────────────────────────────────────────────
	ListEffectiveRoles(ctx context.Context, arg ListEffectiveRolesParams) ([]pgtype.Text, error)
	ListGoogleLinks(ctx context.Context, pSubject string) ([]VwLinkedidentityowner, error)
	ListGroupManagers(ctx context.Context, arg ListGroupManagersParams) ([]VwGroupmanager, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: groups, and the App Central scopes groups and people hold
	//
	// Tenant ownership for the scope writes is enforced inside stp_SetGroupScopes
	// and stp_SetUserScopes, which look the group or user up by (id, tenant). The
	// API cannot bypass it by passing a foreign id.
	// ─────────────────────────────────────────────────────────────────────────────
	ListGroups(ctx context.Context, pClientid string) ([]VwGrouplistitem, error)
	ListInvitationGroups(ctx context.Context, pInvitationid string) ([]VwInvitationgroup, error)
	ListInvitations(ctx context.Context, pClientid string) ([]VwInvitationlistitem, error)
	ListLoginCandidates(ctx context.Context, pEmail string) ([]VwUsercredential, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: login policies and login discovery
	//
	// Which policy applies to a user is resolved in vw_UserLoginPolicy (users.sql);
	// these are the Owner's management entry points and the domain-only discovery
	// hint the login page uses.
	// ─────────────────────────────────────────────────────────────────────────────
	ListLoginPolicies(ctx context.Context, pClientid string) ([]TblLoginPolicy, error)
	ListManagedGroups(ctx context.Context, arg ListManagedGroupsParams) ([]VwGrouplistitem, error)
	ListProductRedirectUris(ctx context.Context, pProductid string) ([]TblProductRedirectUri, error)
	ListProductRoles(ctx context.Context, pProductid string) ([]TblProductRole, error)
	ListProducts(ctx context.Context) ([]VwProductclient, error)
	// Rule 2's measure of a person: the distinct scopes they hold or can hand out
	// as a group's manager. Never used to grant anything.
	ListScopeReach(ctx context.Context, arg ListScopeReachParams) ([]string, error)
	ListScopes(ctx context.Context) ([]TblScope, error)
	ListSessionFamilies(ctx context.Context, pClientid string) ([]VwSessionfamilysummary, error)
	ListSsoConnections(ctx context.Context, pClientid string) ([]VwSsoconnectionsummary, error)
	ListUserApps(ctx context.Context, arg ListUserAppsParams) ([]VwUserapp, error)
	ListUserEffectiveAccess(ctx context.Context, arg ListUserEffectiveAccessParams) ([]VwEffectiveproductrole, error)
	ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]VwUsergroupmembership, error)
	ListUserIdentitiesByEmail(ctx context.Context, pEmail string) ([]VwUseridentity, error)
	ListUserProductRoles(ctx context.Context, arg ListUserProductRolesParams) ([]VwUserproductrole, error)
	ListUserScopes(ctx context.Context, arg ListUserScopesParams) ([]VwEffectivescope, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]VwUserlistitem, error)
	ManagerAddGroupMember(ctx context.Context, arg ManagerAddGroupMemberParams) (int32, error)
	ManagerRemoveGroupMember(ctx context.Context, arg ManagerRemoveGroupMemberParams) (int32, error)
	MarkResetTokenUsed(ctx context.Context, pTokenid string) error
	MarkSessionReplaced(ctx context.Context, arg MarkSessionReplacedParams) error
	// Filtered so an unknown product yields zero rows (see entitlements.sql).
	ProductKeyById(ctx context.Context, pProductid string) (string, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// API surface: shared rate limiting
	//
	// Fixed-window counters kept in the database so several API instances enforce one
	// budget together. RateLimitHit spends a unit atomically (the upsert's row lock
	// serialises concurrent hits of a key across instances); RateLimitPeek reads a
	// key's state without spending; CleanupRateLimitCounters is the periodic sweep.
	// ─────────────────────────────────────────────────────────────────────────────
	RateLimitHit(ctx context.Context, arg RateLimitHitParams) (pgtype.Timestamptz, error)
	RateLimitPeek(ctx context.Context, arg RateLimitPeekParams) (pgtype.Timestamptz, error)
	RemoveGroupManager(ctx context.Context, arg RemoveGroupManagerParams) (int32, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int32, error)
	RevokeAllClientSessions(ctx context.Context, arg RevokeAllClientSessionsParams) (int32, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int32, error)
	RevokeApiClientSecret(ctx context.Context, arg RevokeApiClientSecretParams) (int32, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int32, error)
	RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) (int32, error)
	RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error
	SetApiClientProducts(ctx context.Context, arg SetApiClientProductsParams) (int32, error)
	SetApiClientScopes(ctx context.Context, arg SetApiClientScopesParams) (int32, error)
	SetClientDomain(ctx context.Context, arg SetClientDomainParams) (TblClient, error)
	SetCodeIssuedFamily(ctx context.Context, arg SetCodeIssuedFamilyParams) error
	SetDefaultLoginPolicy(ctx context.Context, arg SetDefaultLoginPolicyParams) (int32, error)
	SetGroupLoginPolicy(ctx context.Context, arg SetGroupLoginPolicyParams) (int32, error)
	SetGroupProductGrants(ctx context.Context, arg SetGroupProductGrantsParams) (int32, error)
	SetGroupScopes(ctx context.Context, arg SetGroupScopesParams) (int32, error)
	SetInvitationAcceptedBy(ctx context.Context, arg SetInvitationAcceptedByParams) error
	SetProductClientSecret(ctx context.Context, arg SetProductClientSecretParams) (int32, error)
	SetProductRedirectUris(ctx context.Context, arg SetProductRedirectUrisParams) (int32, error)
	SetProductRoles(ctx context.Context, arg SetProductRolesParams) (int32, error)
	SetSsoConnectionDomains(ctx context.Context, arg SetSsoConnectionDomainsParams) (int32, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (int32, error)
	SetUserLoginPolicy(ctx context.Context, arg SetUserLoginPolicyParams) (int32, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserScopes(ctx context.Context, arg SetUserScopesParams) (int32, error)
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	TakeLoginState(ctx context.Context, arg TakeLoginStateParams) (TblLoginState, error)
	TouchApiClientSecret(ctx context.Context, arg TouchApiClientSecretParams) error
	UpdateApiClient(ctx context.Context, arg UpdateApiClientParams) (TblApiClient, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (TblClient, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (TblGroup, error)
	UpdateLoginPolicy(ctx context.Context, arg UpdateLoginPolicyParams) (TblLoginPolicy, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (TblProduct, error)
	UpdateSsoConnection(ctx context.Context, arg UpdateSsoConnectionParams) (TblSsoConnection, error)
	UpsertProductPermission(ctx context.Context, arg UpsertProductPermissionParams) error
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (TblClientProduct, error)
	// Filtered so an unresolvable cursor yields zero rows (see entitlements.sql).
	UserCursorPosition(ctx context.Context, arg UserCursorPositionParams) (pgtype.Timestamptz, error)
	// Filtered so an unknown address yields zero rows (see entitlements.sql).
	UserIdByEmail(ctx context.Context, arg UserIdByEmailParams) (string, error)
}

var _ Querier = (*Queries)(nil)
