// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratelimit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupRateLimitCounters = `-- name: CleanupRateLimitCounters :one
SELECT stp_CleanupRateLimitCounters()
`

func (q *Queries) CleanupRateLimitCounters(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, cleanupRateLimitCounters)
	var stp_cleanupratelimitcounters int32
	err := row.Scan(&stp_cleanupratelimitcounters)
	return stp_cleanupratelimitcounters, err
}

const rateLimitHit = `-- name: RateLimitHit :one

SELECT stp_RateLimitHit($1, $2, $3)
`

type RateLimitHitParams struct {
	PKey        string
	PMax        int32
	PWindowsecs int32
}

// ─────────────────────────────────────────────────────────────────────────────
// API surface: shared rate limiting
//
// Fixed-window counters kept in the database so several API instances enforce one
// budget together. RateLimitHit spends a unit atomically (the upsert's row lock
// serialises concurrent hits of a key across instances); RateLimitPeek reads a
// key's state without spending; CleanupRateLimitCounters is the periodic sweep.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) RateLimitHit(ctx context.Context, arg RateLimitHitParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, rateLimitHit, arg.PKey, arg.PMax, arg.PWindowsecs)
	var stp_ratelimithit pgtype.Timestamptz
	err := row.Scan(&stp_ratelimithit)
	return stp_ratelimithit, err
}

const rateLimitPeek = `-- name: RateLimitPeek :one
SELECT udf_RateLimitPeek($1, $2)
`

type RateLimitPeekParams struct {
	PKey string
	PMax int32
}

func (q *Queries) RateLimitPeek(ctx context.Context, arg RateLimitPeekParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, rateLimitPeek, arg.PKey, arg.PMax)
	var udf_ratelimitpeek pgtype.Timestamptz
	err := row.Scan(&udf_ratelimitpeek)
	return udf_ratelimitpeek, err
}
