// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupManager = `-- name: AddGroupManager :one
SELECT stp_AddGroupManager(
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type AddGroupManagerParams struct {
	GroupID   string
	ClientID  string
	UserID    string
	ByUserID  pgtype.Text
	ByOwnerID pgtype.Text
}

func (q *Queries) AddGroupManager(ctx context.Context, arg AddGroupManagerParams) (int32, error) {
	row := q.db.QueryRow(ctx, addGroupManager,
		arg.GroupID,
		arg.ClientID,
		arg.UserID,
		arg.ByUserID,
		arg.ByOwnerID,
	)
	var stp_addgroupmanager int32
	err := row.Scan(&stp_addgroupmanager)
	return stp_addgroupmanager, err
}

const addGroupMember = `-- name: AddGroupMember :exec
CALL stp_AddGroupMember(
    $1,
    $2,
    $3,
    $4
)
`

type AddGroupMemberParams struct {
	UserID     string
	GroupID    string
	ClientID   string
	AssignedBy pgtype.Text
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.ClientID,
		arg.AssignedBy,
	)
	return err
}

const createGroup = `-- name: CreateGroup :one
SELECT id, client_id, name, description, system_key, login_policy_id, created_at, updated_at FROM stp_CreateGroup(
    $1,
    $2,
    $3
)
`

type CreateGroupParams struct {
	ClientID    string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (TblGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.ClientID, arg.Name, arg.Description)
	var i TblGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.SystemKey,
		&i.LoginPolicyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :one
SELECT stp_DeleteGroup($1, $2)
`

type DeleteGroupParams struct {
	PGroupid  string
	PClientid string
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteGroup, arg.PGroupid, arg.PClientid)
	var stp_deletegroup int32
	err := row.Scan(&stp_deletegroup)
	return stp_deletegroup, err
}

const getGroupDetail = `-- name: GetGroupDetail :many
SELECT id, client_id, name, description, system_key, login_policy_id, created_at, scopes, product_grants, user_id, user_email, assigned_at FROM udf_GetGroupDetail($1, $2)
`

type GetGroupDetailParams struct {
	PGroupid  string
	PClientid string
}

func (q *Queries) GetGroupDetail(ctx context.Context, arg GetGroupDetailParams) ([]VwGroupdetailrow, error) {
	rows, err := q.db.Query(ctx, getGroupDetail, arg.PGroupid, arg.PClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwGroupdetailrow{}
	for rows.Next() {
		var i VwGroupdetailrow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.SystemKey,
			&i.LoginPolicyID,
			&i.CreatedAt,
			&i.Scopes,
			&i.ProductGrants,
			&i.UserID,
			&i.UserEmail,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupTenantScoped = `-- name: GetGroupTenantScoped :one
SELECT id, client_id, name, description, system_key, login_policy_id, created_at, updated_at FROM udf_GetGroupTenantScoped($1, $2)
`

type GetGroupTenantScopedParams struct {
	PGroupid  string
	PClientid string
}

func (q *Queries) GetGroupTenantScoped(ctx context.Context, arg GetGroupTenantScopedParams) (TblGroup, error) {
	row := q.db.QueryRow(ctx, getGroupTenantScoped, arg.PGroupid, arg.PClientid)
	var i TblGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.SystemKey,
		&i.LoginPolicyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemGroupId = `-- name: GetSystemGroupId :one
SELECT id FROM (SELECT udf_GetSystemGroupId($1, $2) AS id) t WHERE id IS NOT NULL
`

type GetSystemGroupIdParams struct {
	PClientid  string
	PSystemkey string
}

// Filtered so a missing system group yields zero rows (see entitlements.sql).
func (q *Queries) GetSystemGroupId(ctx context.Context, arg GetSystemGroupIdParams) (string, error) {
	row := q.db.QueryRow(ctx, getSystemGroupId, arg.PClientid, arg.PSystemkey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const isGroupManager = `-- name: IsGroupManager :one
SELECT udf_IsGroupManager(
    $1,
    $2,
    $3
)
`

type IsGroupManagerParams struct {
	GroupID  string
	ClientID string
	UserID   string
}

func (q *Queries) IsGroupManager(ctx context.Context, arg IsGroupManagerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupManager, arg.GroupID, arg.ClientID, arg.UserID)
	var udf_isgroupmanager bool
	err := row.Scan(&udf_isgroupmanager)
	return udf_isgroupmanager, err
}

const listGroupManagers = `-- name: ListGroupManagers :many
SELECT group_id, client_id, user_id, email, appointed_at, appointed_by_email, appointed_by_owner FROM udf_ListGroupManagers(
    $1,
    $2
)
`

type ListGroupManagersParams struct {
	GroupID  string
	ClientID string
}

func (q *Queries) ListGroupManagers(ctx context.Context, arg ListGroupManagersParams) ([]VwGroupmanager, error) {
	rows, err := q.db.Query(ctx, listGroupManagers, arg.GroupID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwGroupmanager{}
	for rows.Next() {
		var i VwGroupmanager
		if err := rows.Scan(
			&i.GroupID,
			&i.ClientID,
			&i.UserID,
			&i.Email,
			&i.AppointedAt,
			&i.AppointedByEmail,
			&i.AppointedByOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many

SELECT id, client_id, name, description, system_key, login_policy_id, created_at, updated_at, scopes, product_grants, member_count FROM udf_ListGroups($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: groups, and the App Central scopes groups and people hold
//
// Tenant ownership for the scope writes is enforced inside stp_SetGroupScopes
// and stp_SetUserScopes, which look the group or user up by (id, tenant). The
// API cannot bypass it by passing a foreign id.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) ListGroups(ctx context.Context, pClientid string) ([]VwGrouplistitem, error) {
	rows, err := q.db.Query(ctx, listGroups, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwGrouplistitem{}
	for rows.Next() {
		var i VwGrouplistitem
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.SystemKey,
			&i.LoginPolicyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scopes,
			&i.ProductGrants,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedGroups = `-- name: ListManagedGroups :many
SELECT id, client_id, name, description, system_key, login_policy_id, created_at, updated_at, scopes, product_grants, member_count FROM udf_ListManagedGroups(
    $1,
    $2
)
`

type ListManagedGroupsParams struct {
	UserID   string
	ClientID string
}

func (q *Queries) ListManagedGroups(ctx context.Context, arg ListManagedGroupsParams) ([]VwGrouplistitem, error) {
	rows, err := q.db.Query(ctx, listManagedGroups, arg.UserID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwGrouplistitem{}
	for rows.Next() {
		var i VwGrouplistitem
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.SystemKey,
			&i.LoginPolicyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scopes,
			&i.ProductGrants,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeReach = `-- name: ListScopeReach :many
SELECT DISTINCT v.scope FROM udf_ListScopeReach(
    $1,
    $2
) v
ORDER BY v.scope
`

type ListScopeReachParams struct {
	ClientID string
	UserID   string
}

// Rule 2's measure of a person: the distinct scopes they hold or can hand out
// as a group's manager. Never used to grant anything.
func (q *Queries) ListScopeReach(ctx context.Context, arg ListScopeReachParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listScopeReach, arg.ClientID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopes = `-- name: ListScopes :many
SELECT scope, kind, feature, level, description, sort_order FROM udf_ListScopes()
`

func (q *Queries) ListScopes(ctx context.Context) ([]TblScope, error) {
	rows, err := q.db.Query(ctx, listScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblScope{}
	for rows.Next() {
		var i TblScope
		if err := rows.Scan(
			&i.Scope,
			&i.Kind,
			&i.Feature,
			&i.Level,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserScopes = `-- name: ListUserScopes :many
SELECT user_id, client_id, scope, source, group_id, group_name FROM udf_ListUserScopes(
    $1,
    $2
)
`

type ListUserScopesParams struct {
	ClientID string
	UserID   string
}

func (q *Queries) ListUserScopes(ctx context.Context, arg ListUserScopesParams) ([]VwEffectivescope, error) {
	rows, err := q.db.Query(ctx, listUserScopes, arg.ClientID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwEffectivescope{}
	for rows.Next() {
		var i VwEffectivescope
		if err := rows.Scan(
			&i.UserID,
			&i.ClientID,
			&i.Scope,
			&i.Source,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerAddGroupMember = `-- name: ManagerAddGroupMember :one
SELECT stp_ManagerAddGroupMember(
    $1,
    $2,
    $3,
    $4
)
`

type ManagerAddGroupMemberParams struct {
	ManagerID string
	UserID    string
	GroupID   string
	ClientID  string
}

func (q *Queries) ManagerAddGroupMember(ctx context.Context, arg ManagerAddGroupMemberParams) (int32, error) {
	row := q.db.QueryRow(ctx, managerAddGroupMember,
		arg.ManagerID,
		arg.UserID,
		arg.GroupID,
		arg.ClientID,
	)
	var stp_manageraddgroupmember int32
	err := row.Scan(&stp_manageraddgroupmember)
	return stp_manageraddgroupmember, err
}

const managerRemoveGroupMember = `-- name: ManagerRemoveGroupMember :one
SELECT stp_ManagerRemoveGroupMember(
    $1,
    $2,
    $3,
    $4
)
`

type ManagerRemoveGroupMemberParams struct {
	ManagerID string
	UserID    string
	GroupID   string
	ClientID  string
}

func (q *Queries) ManagerRemoveGroupMember(ctx context.Context, arg ManagerRemoveGroupMemberParams) (int32, error) {
	row := q.db.QueryRow(ctx, managerRemoveGroupMember,
		arg.ManagerID,
		arg.UserID,
		arg.GroupID,
		arg.ClientID,
	)
	var stp_managerremovegroupmember int32
	err := row.Scan(&stp_managerremovegroupmember)
	return stp_managerremovegroupmember, err
}

const removeGroupManager = `-- name: RemoveGroupManager :one
SELECT stp_RemoveGroupManager(
    $1,
    $2,
    $3
)
`

type RemoveGroupManagerParams struct {
	GroupID  string
	ClientID string
	UserID   string
}

func (q *Queries) RemoveGroupManager(ctx context.Context, arg RemoveGroupManagerParams) (int32, error) {
	row := q.db.QueryRow(ctx, removeGroupManager, arg.GroupID, arg.ClientID, arg.UserID)
	var stp_removegroupmanager int32
	err := row.Scan(&stp_removegroupmanager)
	return stp_removegroupmanager, err
}

const removeGroupMember = `-- name: RemoveGroupMember :one
SELECT stp_RemoveGroupMember($1, $2, $3)
`

type RemoveGroupMemberParams struct {
	PUserid   string
	PGroupid  string
	PClientid string
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int32, error) {
	row := q.db.QueryRow(ctx, removeGroupMember, arg.PUserid, arg.PGroupid, arg.PClientid)
	var stp_removegroupmember int32
	err := row.Scan(&stp_removegroupmember)
	return stp_removegroupmember, err
}

const setGroupLoginPolicy = `-- name: SetGroupLoginPolicy :one
SELECT stp_SetGroupLoginPolicy(
    $1,
    $2,
    $3
)
`

type SetGroupLoginPolicyParams struct {
	GroupID  string
	ClientID string
	PolicyID pgtype.Text
}

func (q *Queries) SetGroupLoginPolicy(ctx context.Context, arg SetGroupLoginPolicyParams) (int32, error) {
	row := q.db.QueryRow(ctx, setGroupLoginPolicy, arg.GroupID, arg.ClientID, arg.PolicyID)
	var stp_setgrouploginpolicy int32
	err := row.Scan(&stp_setgrouploginpolicy)
	return stp_setgrouploginpolicy, err
}

const setGroupProductGrants = `-- name: SetGroupProductGrants :one
SELECT stp_SetGroupProductGrants(
    $1,
    $2,
    $3::text[],
    $4::text[],
    $5
)
`

type SetGroupProductGrantsParams struct {
	GroupID    string
	ClientID   string
	ProductIds []string
	RoleNames  []string
	GrantedBy  pgtype.Text
}

func (q *Queries) SetGroupProductGrants(ctx context.Context, arg SetGroupProductGrantsParams) (int32, error) {
	row := q.db.QueryRow(ctx, setGroupProductGrants,
		arg.GroupID,
		arg.ClientID,
		arg.ProductIds,
		arg.RoleNames,
		arg.GrantedBy,
	)
	var stp_setgroupproductgrants int32
	err := row.Scan(&stp_setgroupproductgrants)
	return stp_setgroupproductgrants, err
}

const setGroupScopes = `-- name: SetGroupScopes :one
SELECT stp_SetGroupScopes(
    $1,
    $2,
    $3::text[]
)
`

type SetGroupScopesParams struct {
	GroupID  string
	ClientID string
	Scopes   []string
}

func (q *Queries) SetGroupScopes(ctx context.Context, arg SetGroupScopesParams) (int32, error) {
	row := q.db.QueryRow(ctx, setGroupScopes, arg.GroupID, arg.ClientID, arg.Scopes)
	var stp_setgroupscopes int32
	err := row.Scan(&stp_setgroupscopes)
	return stp_setgroupscopes, err
}

const setUserScopes = `-- name: SetUserScopes :one
SELECT stp_SetUserScopes(
    $1,
    $2,
    $3::text[],
    $4,
    $5
)
`

type SetUserScopesParams struct {
	UserID           string
	ClientID         string
	Scopes           []string
	GrantedByUserID  pgtype.Text
	GrantedByOwnerID pgtype.Text
}

func (q *Queries) SetUserScopes(ctx context.Context, arg SetUserScopesParams) (int32, error) {
	row := q.db.QueryRow(ctx, setUserScopes,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.GrantedByUserID,
		arg.GrantedByOwnerID,
	)
	var stp_setuserscopes int32
	err := row.Scan(&stp_setuserscopes)
	return stp_setuserscopes, err
}

const updateGroup = `-- name: UpdateGroup :one
SELECT id, client_id, name, description, system_key, login_policy_id, created_at, updated_at FROM stp_UpdateGroup(
    $1,
    $2,
    $3,
    $4
)
`

type UpdateGroupParams struct {
	GroupID     string
	ClientID    string
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (TblGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.GroupID,
		arg.ClientID,
		arg.Name,
		arg.Description,
	)
	var i TblGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.SystemKey,
		&i.LoginPolicyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
