// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCentralFamily = `-- name: CreateCentralFamily :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM stp_CreateCentralFamily(
    $1,
    $2,
    $3::"IdpProvider",
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateCentralFamilyParams struct {
	UserID            string
	ClientID          string
	AuthMethod        IdpProvider
	AuthConnectionID  pgtype.Text
	AbsoluteExpiresAt pgtype.Timestamptz
	SessionUuid       string
	RefreshTokenHash  string
	ExpiresAt         pgtype.Timestamptz
	IpAddress         pgtype.Text
	DeviceLabel       pgtype.Text
	UserAgent         pgtype.Text
}

func (q *Queries) CreateCentralFamily(ctx context.Context, arg CreateCentralFamilyParams) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, createCentralFamily,
		arg.UserID,
		arg.ClientID,
		arg.AuthMethod,
		arg.AuthConnectionID,
		arg.AbsoluteExpiresAt,
		arg.SessionUuid,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.DeviceLabel,
		arg.UserAgent,
	)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const createProductFamily = `-- name: CreateProductFamily :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM stp_CreateProductFamily(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type CreateProductFamilyParams struct {
	ParentFamilyID   string
	UserID           string
	ClientID         string
	ProductID        string
	SessionUuid      string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	IpAddress        pgtype.Text
	DeviceLabel      pgtype.Text
	UserAgent        pgtype.Text
}

func (q *Queries) CreateProductFamily(ctx context.Context, arg CreateProductFamilyParams) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, createProductFamily,
		arg.ParentFamilyID,
		arg.UserID,
		arg.ClientID,
		arg.ProductID,
		arg.SessionUuid,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.DeviceLabel,
		arg.UserAgent,
	)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const createSuccessorSession = `-- name: CreateSuccessorSession :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM stp_CreateSuccessorSession(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateSuccessorSessionParams struct {
	UserID           string
	ClientID         string
	SessionUuid      string
	FamilyID         string
	Generation       int32
	RefreshTokenHash string
	PrevTokenHash    pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	IpAddress        pgtype.Text
	DeviceLabel      pgtype.Text
	UserAgent        pgtype.Text
}

func (q *Queries) CreateSuccessorSession(ctx context.Context, arg CreateSuccessorSessionParams) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, createSuccessorSession,
		arg.UserID,
		arg.ClientID,
		arg.SessionUuid,
		arg.FamilyID,
		arg.Generation,
		arg.RefreshTokenHash,
		arg.PrevTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.DeviceLabel,
		arg.UserAgent,
	)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const expireSessions = `-- name: ExpireSessions :exec
CALL stp_ExpireSessions($1)
`

func (q *Queries) ExpireSessions(ctx context.Context, pBatchsize int32) error {
	_, err := q.db.Exec(ctx, expireSessions, pBatchsize)
	return err
}

const getGraceSuccessor = `-- name: GetGraceSuccessor :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM udf_GetGraceSuccessor($1, $2)
`

type GetGraceSuccessorParams struct {
	PPrevtokenhash string
	PCreatedafter  pgtype.Timestamptz
}

func (q *Queries) GetGraceSuccessor(ctx context.Context, arg GetGraceSuccessorParams) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, getGraceSuccessor, arg.PPrevtokenhash, arg.PCreatedafter)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM udf_GetSessionById($1)
`

func (q *Queries) GetSessionById(ctx context.Context, pSessionid string) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, getSessionById, pSessionid)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getSessionByRefreshHashForUpdate = `-- name: GetSessionByRefreshHashForUpdate :one

SELECT id, user_id, client_id, session_uuid, family_id, generation, refresh_token_hash, prev_token_hash, expires_at, revoked_at, revoked_reason, ip_address, device_label, user_agent, last_seen_at, created_at, replaced_by_id FROM udf_GetSessionByRefreshHashForUpdate($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: sessions (logins and refresh-token rotation)
//
// A login is a family (tbl_session_families); each refresh appends a generation
// (tbl_user_sessions). The rotation sequence is orchestrated by the API inside
// ONE transaction, but every individual statement is a database object. In
// particular the lock is taken by udf_GetSessionByRefreshHashForUpdate, so the
// FOR UPDATE that serialises concurrent rotations lives in the database.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetSessionByRefreshHashForUpdate(ctx context.Context, pTokenhash string) (TblUserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHashForUpdate, pTokenhash)
	var i TblUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionUuid,
		&i.FamilyID,
		&i.Generation,
		&i.RefreshTokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getSessionFamilyGate = `-- name: GetSessionFamilyGate :one
SELECT family_id, user_id, client_id, kind, product_id, parent_family_id, auth_method, auth_connection_id, authenticated_at, absolute_expires_at, family_alive, parent_alive, user_active, client_active, email, permissions_version, is_tenant_admin, is_platform_owner, has_access, admin_version, scopes FROM udf_GetSessionFamilyGate($1)
`

func (q *Queries) GetSessionFamilyGate(ctx context.Context, pFamilyid string) (VwSessionfamilygate, error) {
	row := q.db.QueryRow(ctx, getSessionFamilyGate, pFamilyid)
	var i VwSessionfamilygate
	err := row.Scan(
		&i.FamilyID,
		&i.UserID,
		&i.ClientID,
		&i.Kind,
		&i.ProductID,
		&i.ParentFamilyID,
		&i.AuthMethod,
		&i.AuthConnectionID,
		&i.AuthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.FamilyAlive,
		&i.ParentAlive,
		&i.UserActive,
		&i.ClientActive,
		&i.Email,
		&i.PermissionsVersion,
		&i.IsTenantAdmin,
		&i.IsPlatformOwner,
		&i.HasAccess,
		&i.AdminVersion,
		&i.Scopes,
	)
	return i, err
}

const getSessionForLogout = `-- name: GetSessionForLogout :one
SELECT id, family_id, user_id, client_id, revoked_at, refresh_token_hash FROM udf_GetSessionForLogout($1)
`

func (q *Queries) GetSessionForLogout(ctx context.Context, pTokenhash string) (VwSessionowner, error) {
	row := q.db.QueryRow(ctx, getSessionForLogout, pTokenhash)
	var i VwSessionowner
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.ClientID,
		&i.RevokedAt,
		&i.RefreshTokenHash,
	)
	return i, err
}

const listSessionFamilies = `-- name: ListSessionFamilies :many
SELECT id, client_id, kind, product_key, auth_method, authenticated_at, created_at, device_label, ip_address, last_seen_at, email FROM udf_ListSessionFamilies($1)
`

func (q *Queries) ListSessionFamilies(ctx context.Context, pClientid string) ([]VwSessionfamilysummary, error) {
	rows, err := q.db.Query(ctx, listSessionFamilies, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwSessionfamilysummary{}
	for rows.Next() {
		var i VwSessionfamilysummary
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Kind,
			&i.ProductKey,
			&i.AuthMethod,
			&i.AuthenticatedAt,
			&i.CreatedAt,
			&i.DeviceLabel,
			&i.IpAddress,
			&i.LastSeenAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionReplaced = `-- name: MarkSessionReplaced :exec
CALL stp_MarkSessionReplaced($1, $2)
`

type MarkSessionReplacedParams struct {
	PSessionid    string
	PReplacedbyid string
}

func (q *Queries) MarkSessionReplaced(ctx context.Context, arg MarkSessionReplacedParams) error {
	_, err := q.db.Exec(ctx, markSessionReplaced, arg.PSessionid, arg.PReplacedbyid)
	return err
}

const revokeAllClientSessions = `-- name: RevokeAllClientSessions :one
SELECT stp_RevokeAllClientSessions(
    $1,
    $2::"SessionRevokedReason"
)
`

type RevokeAllClientSessionsParams struct {
	ClientID string
	Reason   SessionRevokedReason
}

func (q *Queries) RevokeAllClientSessions(ctx context.Context, arg RevokeAllClientSessionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeAllClientSessions, arg.ClientID, arg.Reason)
	var stp_revokeallclientsessions int32
	err := row.Scan(&stp_revokeallclientsessions)
	return stp_revokeallclientsessions, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :one
SELECT stp_RevokeAllUserSessions(
    $1,
    $2::"SessionRevokedReason"
)
`

type RevokeAllUserSessionsParams struct {
	UserID string
	Reason SessionRevokedReason
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeAllUserSessions, arg.UserID, arg.Reason)
	var stp_revokeallusersessions int32
	err := row.Scan(&stp_revokeallusersessions)
	return stp_revokeallusersessions, err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :one
SELECT stp_RevokeSessionFamily(
    $1,
    $2,
    $3::"SessionRevokedReason"
)
`

type RevokeSessionFamilyParams struct {
	FamilyID string
	ClientID string
	Reason   SessionRevokedReason
}

func (q *Queries) RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeSessionFamily, arg.FamilyID, arg.ClientID, arg.Reason)
	var stp_revokesessionfamily int32
	err := row.Scan(&stp_revokesessionfamily)
	return stp_revokesessionfamily, err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
CALL stp_RevokeTokenFamily($1, $2)
`

type RevokeTokenFamilyParams struct {
	PFamilyid string
	PReason   string
}

func (q *Queries) RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, arg.PFamilyid, arg.PReason)
	return err
}
