// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSsoConnection = `-- name: CreateSsoConnection :one
SELECT id, client_id, name, issuer, oidc_client_id, client_secret_ciphertext, secret_key_id, scopes, trust_unverified_email, is_active, created_at, updated_at FROM stp_CreateSsoConnection(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type CreateSsoConnectionParams struct {
	ConnectionID         string
	ClientID             string
	Name                 string
	Issuer               string
	OidcClientID         string
	SecretCiphertext     []byte
	SecretKeyID          pgtype.Text
	Scopes               string
	TrustUnverifiedEmail bool
	IsActive             bool
}

func (q *Queries) CreateSsoConnection(ctx context.Context, arg CreateSsoConnectionParams) (TblSsoConnection, error) {
	row := q.db.QueryRow(ctx, createSsoConnection,
		arg.ConnectionID,
		arg.ClientID,
		arg.Name,
		arg.Issuer,
		arg.OidcClientID,
		arg.SecretCiphertext,
		arg.SecretKeyID,
		arg.Scopes,
		arg.TrustUnverifiedEmail,
		arg.IsActive,
	)
	var i TblSsoConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Issuer,
		&i.OidcClientID,
		&i.ClientSecretCiphertext,
		&i.SecretKeyID,
		&i.Scopes,
		&i.TrustUnverifiedEmail,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSsoConnection = `-- name: GetSsoConnection :one

SELECT id, client_id, name, issuer, oidc_client_id, client_secret_ciphertext, secret_key_id, scopes, trust_unverified_email, is_active, domains FROM udf_GetSsoConnection($1)
`

// ─────────────────────────────────────────────────────────────────────────────
// API surface: tenants' own OIDC identity providers
//
// The client secret enters and leaves only as ciphertext; the key that decrypts
// it is held by the API, never by the database.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) GetSsoConnection(ctx context.Context, pConnectionid string) (VwSsoconnectionruntime, error) {
	row := q.db.QueryRow(ctx, getSsoConnection, pConnectionid)
	var i VwSsoconnectionruntime
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Issuer,
		&i.OidcClientID,
		&i.ClientSecretCiphertext,
		&i.SecretKeyID,
		&i.Scopes,
		&i.TrustUnverifiedEmail,
		&i.IsActive,
		&i.Domains,
	)
	return i, err
}

const listSsoConnections = `-- name: ListSsoConnections :many
SELECT id, client_id, name, issuer, oidc_client_id, scopes, trust_unverified_email, is_active, has_secret, domains, created_at, updated_at FROM udf_ListSsoConnections($1)
`

func (q *Queries) ListSsoConnections(ctx context.Context, pClientid string) ([]VwSsoconnectionsummary, error) {
	rows, err := q.db.Query(ctx, listSsoConnections, pClientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwSsoconnectionsummary{}
	for rows.Next() {
		var i VwSsoconnectionsummary
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Issuer,
			&i.OidcClientID,
			&i.Scopes,
			&i.TrustUnverifiedEmail,
			&i.IsActive,
			&i.HasSecret,
			&i.Domains,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSsoConnectionDomains = `-- name: SetSsoConnectionDomains :one
SELECT stp_SetSsoConnectionDomains(
    $1,
    $2,
    $3::text[]
)
`

type SetSsoConnectionDomainsParams struct {
	ConnectionID string
	ClientID     string
	Domains      []string
}

func (q *Queries) SetSsoConnectionDomains(ctx context.Context, arg SetSsoConnectionDomainsParams) (int32, error) {
	row := q.db.QueryRow(ctx, setSsoConnectionDomains, arg.ConnectionID, arg.ClientID, arg.Domains)
	var stp_setssoconnectiondomains int32
	err := row.Scan(&stp_setssoconnectiondomains)
	return stp_setssoconnectiondomains, err
}

const updateSsoConnection = `-- name: UpdateSsoConnection :one
SELECT id, client_id, name, issuer, oidc_client_id, client_secret_ciphertext, secret_key_id, scopes, trust_unverified_email, is_active, created_at, updated_at FROM stp_UpdateSsoConnection(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type UpdateSsoConnectionParams struct {
	ConnectionID         string
	ClientID             string
	Name                 string
	Issuer               string
	OidcClientID         string
	SecretCiphertext     []byte
	SecretKeyID          pgtype.Text
	Scopes               string
	TrustUnverifiedEmail bool
	IsActive             bool
}

func (q *Queries) UpdateSsoConnection(ctx context.Context, arg UpdateSsoConnectionParams) (TblSsoConnection, error) {
	row := q.db.QueryRow(ctx, updateSsoConnection,
		arg.ConnectionID,
		arg.ClientID,
		arg.Name,
		arg.Issuer,
		arg.OidcClientID,
		arg.SecretCiphertext,
		arg.SecretKeyID,
		arg.Scopes,
		arg.TrustUnverifiedEmail,
		arg.IsActive,
	)
	var i TblSsoConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Issuer,
		&i.OidcClientID,
		&i.ClientSecretCiphertext,
		&i.SecretKeyID,
		&i.Scopes,
		&i.TrustUnverifiedEmail,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
