/****** Database build script ******/
-- Applies every object in dependency order. Idempotent: safe to re-run, which
-- is what makes it usable as both a fresh install and an upgrade.
--
--   psql -v ON_ERROR_STOP=1 -f db/build.sql
--
-- GENERATED by db/gen_build.py -- do not edit by hand.
-- Order matters between layers, not within them:
--   1. Extensions and Types  referenced by column definitions
--   2. Tables                parents first: a foreign key needs its target
--   3. Views                 read from tables
--   4. Functions (udf_)      read from tables and views
--   5. Procedures (stp_)     write to tables

\set ON_ERROR_STOP on

-- 0. Schema version guard ---------------------------------------------------
-- This is the v3 baseline. It cannot upgrade an older database in place (a
-- view cannot drop a column through CREATE OR REPLACE, and CREATE TABLE IF NOT
-- EXISTS adds no column), so it refuses one outright rather than half-applying.
-- See Migrations/README.md.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'tbl_users' AND column_name = 'is_global_admin') THEN
        RAISE EXCEPTION 'v1 schema detected; rebuild the database from scratch (Migrations/README.md)';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_name = 'tbl_group_features') THEN
        RAISE EXCEPTION 'v2 schema detected; rebuild the database from scratch (Migrations/README.md)';
    END IF;
END $$;

-- 1. Extensions and types ---------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()

-- Types: guarded form generated from Programmability/Types/enums.sql
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SubscriptionStatus') THEN
        CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'IdpProvider') THEN
        CREATE TYPE "IdpProvider" AS ENUM ('EMAIL', 'GOOGLE', 'MICROSOFT', 'SAML', 'OIDC');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AccountType') THEN
        CREATE TYPE "AccountType" AS ENUM ('EMAIL', 'OAUTH_ONLY', 'HYBRID');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SessionRevokedReason') THEN
        CREATE TYPE "SessionRevokedReason" AS ENUM ('LOGOUT', 'LOGOUT_ALL', 'REUSE_DETECTED', 'ADMIN', 'EXPIRED', 'POLICY', 'ACCESS_LOST', 'SUSPENDED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'InvitationStatus') THEN
        CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SessionKind') THEN
        CREATE TYPE "SessionKind" AS ENUM ('CENTRAL', 'PRODUCT');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'LoginStateKind') THEN
        CREATE TYPE "LoginStateKind" AS ENUM ('GOOGLE', 'OIDC', 'ACCOUNT_CHOICE');
    END IF;
END $$;

-- 2. Tables -----------------------------------------------------------------
\ir 'Tables/tbl_clients.sql'
\ir 'Tables/tbl_scopes.sql'
\ir 'Tables/tbl_products.sql'
\ir 'Tables/tbl_product_roles.sql'
\ir 'Tables/tbl_product_redirect_uris.sql'
\ir 'Tables/tbl_sso_connections.sql'
\ir 'Tables/tbl_login_policies.sql'
\ir 'Tables/tbl_users.sql'
\ir 'Tables/tbl_platform_owners.sql'
\ir 'Tables/tbl_client_products.sql'
\ir 'Tables/tbl_groups.sql'
\ir 'Tables/tbl_session_families.sql'
\ir 'Tables/tbl_user_sessions.sql'
\ir 'Tables/tbl_product_permissions.sql'
\ir 'Tables/tbl_group_product_grants.sql'
\ir 'Tables/tbl_group_scopes.sql'
\ir 'Tables/tbl_user_scopes.sql'
\ir 'Tables/tbl_api_clients.sql'
\ir 'Tables/tbl_api_client_scopes.sql'
\ir 'Tables/tbl_api_client_products.sql'
\ir 'Tables/tbl_api_client_secrets.sql'
\ir 'Tables/tbl_user_groups.sql'
\ir 'Tables/tbl_group_managers.sql'
\ir 'Tables/tbl_linked_identities.sql'
\ir 'Tables/tbl_invitations.sql'
\ir 'Tables/tbl_invitation_groups.sql'
\ir 'Tables/tbl_audit_logs.sql'
\ir 'Tables/tbl_authorization_codes.sql'
\ir 'Tables/tbl_password_reset_tokens.sql'
\ir 'Tables/tbl_login_states.sql'
\ir 'Tables/tbl_sso_connection_domains.sql'
\ir 'Tables/tbl_rate_limit_counters.sql'
\ir 'Tables/tbl_schema_migrations.sql'

-- 3. Views ------------------------------------------------------------------
\ir 'Views/vw_ApiClientGrant.sql'
\ir 'Views/vw_ApiClientSecret.sql'
\ir 'Views/vw_ApiClientSummary.sql'
\ir 'Views/vw_ClientProductDetail.sql'
\ir 'Views/vw_CompanyListItem.sql'
\ir 'Views/vw_DomainLoginHint.sql'
\ir 'Views/vw_EffectiveProductRole.sql'
\ir 'Views/vw_EffectiveScope.sql'
\ir 'Views/vw_GroupDetailRow.sql'
\ir 'Views/vw_GroupListItem.sql'
\ir 'Views/vw_GroupManager.sql'
\ir 'Views/vw_InvitationGroup.sql'
\ir 'Views/vw_InvitationListItem.sql'
\ir 'Views/vw_LinkedIdentityOwner.sql'
\ir 'Views/vw_OAuthClientCredential.sql'
\ir 'Views/vw_PendingInvitation.sql'
\ir 'Views/vw_ProductClient.sql'
\ir 'Views/vw_ProductClientCredential.sql'
\ir 'Views/vw_ScopeReach.sql'
\ir 'Views/vw_SessionFamilyGate.sql'
\ir 'Views/vw_SessionFamilySummary.sql'
\ir 'Views/vw_SessionOwner.sql'
\ir 'Views/vw_SsoConnectionRuntime.sql'
\ir 'Views/vw_SsoConnectionSummary.sql'
\ir 'Views/vw_UserApp.sql'
\ir 'Views/vw_UserCredential.sql'
\ir 'Views/vw_UserGroupMembership.sql'
\ir 'Views/vw_UserIdentity.sql'
\ir 'Views/vw_UserListItem.sql'
\ir 'Views/vw_UserLoginPolicy.sql'
\ir 'Views/vw_UserProductRole.sql'
\ir 'Views/vw_UserTenantScoped.sql'
\ir 'Views/vw_ValidResetToken.sql'

-- 4. Functions (reads) ------------------------------------------------------
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ActiveEmailExists.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ActiveSubscriptionId.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ClientIdByVerifiedDomain.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ClientNameById.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_GetSystemGroupId.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_HealthCheck.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_IsApiClientSecretLive.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_IsGroupManager.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_IsRedirectUriRegistered.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ProductKeyById.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_RateLimitPeek.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_UserCursorPosition.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_UserIdByEmail.sql'

\ir 'Programmability/Functions/Table-valued Functions/udf_GetApiClient.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetApiClientGrant.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetAuthorizationCodeByHash.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetClientById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetDomainLoginHint.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetGraceSuccessor.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetGroupDetail.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetGroupTenantScoped.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetInvitationLoginPolicy.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetLinkedIdentityByConnection.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetLoginPolicy.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetLoginState.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetOAuthClientCredentials.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetOAuthLinkableUser.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetPendingInvitation.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetPendingInviteByEmail.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetProductById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetProductClient.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetProductClientCredential.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetProductPermission.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSessionById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSessionByRefreshHashForUpdate.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSessionFamilyGate.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSessionForLogout.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSsoConnection.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserForSsoLink.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserIdentityForToken.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserLoginPolicy.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserTenantScoped.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetValidResetToken.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListActiveProducts.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListAllApiClients.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListApiClientProductChoices.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListApiClientSecrets.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListApiClients.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListClientProducts.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListCompanies.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListEffectiveRoles.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListGoogleLinks.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListGroupManagers.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListGroups.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListInvitationGroups.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListInvitations.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListLoginCandidates.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListLoginPolicies.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListManagedGroups.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListProductRedirectUris.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListProductRoles.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListProducts.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListScopeReach.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListScopes.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListSessionFamilies.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListSsoConnections.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserApps.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserEffectiveAccess.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserGroups.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserIdentitiesByEmail.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserProductRoles.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserScopes.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUsers.sql'

-- 5. Procedures (writes) ----------------------------------------------------
\ir 'Programmability/StoredProcedures/stp_AddGroupManager.sql'
\ir 'Programmability/StoredProcedures/stp_AddGroupMember.sql'
\ir 'Programmability/StoredProcedures/stp_AssertProductSeat.sql'
\ir 'Programmability/StoredProcedures/stp_BumpPermissionsVersion.sql'
\ir 'Programmability/StoredProcedures/stp_ClaimAuthorizationCode.sql'
\ir 'Programmability/StoredProcedures/stp_ClaimInvitation.sql'
\ir 'Programmability/StoredProcedures/stp_CleanupExpiredAuthCodes.sql'
\ir 'Programmability/StoredProcedures/stp_CleanupLoginStates.sql'
\ir 'Programmability/StoredProcedures/stp_CleanupRateLimitCounters.sql'
\ir 'Programmability/StoredProcedures/stp_CreateApiClient.sql'
\ir 'Programmability/StoredProcedures/stp_CreateApiClientSecret.sql'
\ir 'Programmability/StoredProcedures/stp_CreateAuthorizationCode.sql'
\ir 'Programmability/StoredProcedures/stp_CreateCentralFamily.sql'
\ir 'Programmability/StoredProcedures/stp_CreateClient.sql'
\ir 'Programmability/StoredProcedures/stp_CreateGroup.sql'
\ir 'Programmability/StoredProcedures/stp_CreateInvitation.sql'
\ir 'Programmability/StoredProcedures/stp_CreateInvitationGroup.sql'
\ir 'Programmability/StoredProcedures/stp_CreateLinkedIdentity.sql'
\ir 'Programmability/StoredProcedures/stp_CreateLoginPolicy.sql'
\ir 'Programmability/StoredProcedures/stp_CreateLoginState.sql'
\ir 'Programmability/StoredProcedures/stp_CreatePlatformOwner.sql'
\ir 'Programmability/StoredProcedures/stp_CreateProduct.sql'
\ir 'Programmability/StoredProcedures/stp_CreateProductFamily.sql'
\ir 'Programmability/StoredProcedures/stp_CreateResetToken.sql'
\ir 'Programmability/StoredProcedures/stp_CreateSsoConnection.sql'
\ir 'Programmability/StoredProcedures/stp_CreateSuccessorSession.sql'
\ir 'Programmability/StoredProcedures/stp_CreateUser.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteApiClient.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteGroup.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteLinkedIdentity.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteLoginPolicy.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteProductPermission.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteUnusedResetTokens.sql'
\ir 'Programmability/StoredProcedures/stp_ExpireInvitations.sql'
\ir 'Programmability/StoredProcedures/stp_ExpireSessions.sql'
\ir 'Programmability/StoredProcedures/stp_InsertAuditLog.sql'
\ir 'Programmability/StoredProcedures/stp_ManagerAddGroupMember.sql'
\ir 'Programmability/StoredProcedures/stp_ManagerRemoveGroupMember.sql'
\ir 'Programmability/StoredProcedures/stp_MarkResetTokenUsed.sql'
\ir 'Programmability/StoredProcedures/stp_MarkSessionReplaced.sql'
\ir 'Programmability/StoredProcedures/stp_RateLimitHit.sql'
\ir 'Programmability/StoredProcedures/stp_RemoveGroupManager.sql'
\ir 'Programmability/StoredProcedures/stp_RemoveGroupMember.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeAllClientSessions.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeAllUserSessions.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeApiClientSecret.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeInvitation.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeSessionFamily.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeTokenFamily.sql'
\ir 'Programmability/StoredProcedures/stp_SetApiClientProducts.sql'
\ir 'Programmability/StoredProcedures/stp_SetApiClientScopes.sql'
\ir 'Programmability/StoredProcedures/stp_SetClientDomain.sql'
\ir 'Programmability/StoredProcedures/stp_SetCodeIssuedFamily.sql'
\ir 'Programmability/StoredProcedures/stp_SetDefaultLoginPolicy.sql'
\ir 'Programmability/StoredProcedures/stp_SetGroupLoginPolicy.sql'
\ir 'Programmability/StoredProcedures/stp_SetGroupProductGrants.sql'
\ir 'Programmability/StoredProcedures/stp_SetGroupScopes.sql'
\ir 'Programmability/StoredProcedures/stp_SetInvitationAcceptedBy.sql'
\ir 'Programmability/StoredProcedures/stp_SetProductClientSecret.sql'
\ir 'Programmability/StoredProcedures/stp_SetProductRedirectUris.sql'
\ir 'Programmability/StoredProcedures/stp_SetProductRoles.sql'
\ir 'Programmability/StoredProcedures/stp_SetSsoConnectionDomains.sql'
\ir 'Programmability/StoredProcedures/stp_SetUserActive.sql'
\ir 'Programmability/StoredProcedures/stp_SetUserLoginPolicy.sql'
\ir 'Programmability/StoredProcedures/stp_SetUserPassword.sql'
\ir 'Programmability/StoredProcedures/stp_SetUserScopes.sql'
\ir 'Programmability/StoredProcedures/stp_SoftDeleteUser.sql'
\ir 'Programmability/StoredProcedures/stp_TakeLoginState.sql'
\ir 'Programmability/StoredProcedures/stp_TouchApiClientSecret.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateApiClient.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateClient.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateGroup.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateLoginPolicy.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateProduct.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateSsoConnection.sql'
\ir 'Programmability/StoredProcedures/stp_UpsertProductPermission.sql'
\ir 'Programmability/StoredProcedures/stp_UpsertSubscription.sql'
