/****** Database build script ******/
-- Applies every object in dependency order. Idempotent: safe to re-run, which
-- is what makes it usable as both a fresh install and an upgrade.
--
--   psql -v ON_ERROR_STOP=1 -f db/build.sql
--
-- GENERATED by db/gen_build.py -- do not edit by hand.
-- Order matters between layers, not within them:
--   1. Extensions and Types  referenced by column definitions
--   2. Tables                foreign keys are guarded, so order is cosmetic
--   3. Views                 read from tables
--   4. Functions (udf_)      read from tables and views
--   5. Procedures (stp_)     write to tables

\set ON_ERROR_STOP on

-- 1. Extensions and types ---------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()

-- Types: guarded form generated from Programmability/Types/enums.sql
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SubscriptionStatus') THEN
        CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'IdpProvider') THEN
        CREATE TYPE "IdpProvider" AS ENUM ('EMAIL', 'GOOGLE', 'MICROSOFT', 'SAML', 'OIDC');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AccountType') THEN
        CREATE TYPE "AccountType" AS ENUM ('EMAIL', 'OAUTH_ONLY', 'HYBRID');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SessionRevokedReason') THEN
        CREATE TYPE "SessionRevokedReason" AS ENUM ('LOGOUT', 'LOGOUT_ALL', 'REUSE_DETECTED', 'ADMIN', 'EXPIRED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'InvitationStatus') THEN
        CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED');
    END IF;
END $$;

-- 2. Tables -----------------------------------------------------------------
\ir 'Tables/tbl_clients.sql'
\ir 'Tables/tbl_products.sql'
\ir 'Tables/tbl_users.sql'
\ir 'Tables/tbl_user_sessions.sql'
\ir 'Tables/tbl_client_products.sql'
\ir 'Tables/tbl_product_permissions.sql'
\ir 'Tables/tbl_linked_identities.sql'
\ir 'Tables/tbl_invitations.sql'
\ir 'Tables/tbl_invitation_products.sql'
\ir 'Tables/tbl_audit_logs.sql'
\ir 'Tables/tbl_authorization_codes.sql'
\ir 'Tables/tbl_groups.sql'
\ir 'Tables/tbl_group_features.sql'
\ir 'Tables/tbl_user_groups.sql'
\ir 'Tables/tbl_password_reset_tokens.sql'
\ir 'Tables/tbl_schema_migrations.sql'

-- 3. Views ------------------------------------------------------------------
\ir 'Views/vw_ClientOAuthGate.sql'
\ir 'Views/vw_ClientProductDetail.sql'
\ir 'Views/vw_GroupDetailRow.sql'
\ir 'Views/vw_GroupListItem.sql'
\ir 'Views/vw_InvitationListItem.sql'
\ir 'Views/vw_InvitationProductRole.sql'
\ir 'Views/vw_LinkedIdentityOwner.sql'
\ir 'Views/vw_PendingInvitation.sql'
\ir 'Views/vw_SessionOwner.sql'
\ir 'Views/vw_SessionSummary.sql'
\ir 'Views/vw_UserCredential.sql'
\ir 'Views/vw_UserFreshness.sql'
\ir 'Views/vw_UserGroupMembership.sql'
\ir 'Views/vw_UserIdentity.sql'
\ir 'Views/vw_UserListItem.sql'
\ir 'Views/vw_UserProductRole.sql'
\ir 'Views/vw_UserTenantScoped.sql'
\ir 'Views/vw_ValidResetToken.sql'

-- 4. Functions (reads) ------------------------------------------------------
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ActiveEmailExists.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ActiveSubscriptionId.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ClientIdByVerifiedDomain.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ClientNameById.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_HasGroupFeature.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_HealthCheck.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_ProductKeyById.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_UserCursorPosition.sql'
\ir 'Programmability/Functions/Scalar-valued Functions/udf_UserIdByEmail.sql'

\ir 'Programmability/Functions/Table-valued Functions/udf_GetClientById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetClientOAuthGate.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetClientSessionById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetGraceSuccessor.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetGroupDetail.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetGroupTenantScoped.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetLinkedIdentity.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetOAuthLinkableUser.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetPendingInvitation.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetPendingInviteByEmail.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetProductById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetProductPermission.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSessionById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSessionByRefreshHashForUpdate.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetSessionForLogout.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserById.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserCredentialByEmail.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserFreshness.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserIdentityForToken.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetUserTenantScoped.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_GetValidResetToken.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListActiveProducts.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListActiveSessions.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListClientProducts.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListGroups.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListInvitationProducts.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListInvitations.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserFeatures.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserGroups.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUserProductRoles.sql'
\ir 'Programmability/Functions/Table-valued Functions/udf_ListUsers.sql'

-- 5. Procedures (writes) ----------------------------------------------------
\ir 'Programmability/StoredProcedures/stp_AddGroupMember.sql'
\ir 'Programmability/StoredProcedures/stp_BumpPermissionsVersion.sql'
\ir 'Programmability/StoredProcedures/stp_ClaimAuthorizationCode.sql'
\ir 'Programmability/StoredProcedures/stp_ClaimInvitation.sql'
\ir 'Programmability/StoredProcedures/stp_CleanupExpiredAuthCodes.sql'
\ir 'Programmability/StoredProcedures/stp_CreateAuthorizationCode.sql'
\ir 'Programmability/StoredProcedures/stp_CreateClient.sql'
\ir 'Programmability/StoredProcedures/stp_CreateGroup.sql'
\ir 'Programmability/StoredProcedures/stp_CreateInvitation.sql'
\ir 'Programmability/StoredProcedures/stp_CreateInvitationProduct.sql'
\ir 'Programmability/StoredProcedures/stp_CreateLinkedIdentity.sql'
\ir 'Programmability/StoredProcedures/stp_CreateProduct.sql'
\ir 'Programmability/StoredProcedures/stp_CreateResetToken.sql'
\ir 'Programmability/StoredProcedures/stp_CreateSession.sql'
\ir 'Programmability/StoredProcedures/stp_CreateSuccessorSession.sql'
\ir 'Programmability/StoredProcedures/stp_CreateUser.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteGroup.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteProductPermission.sql'
\ir 'Programmability/StoredProcedures/stp_DeleteUnusedResetTokens.sql'
\ir 'Programmability/StoredProcedures/stp_ExpireInvitations.sql'
\ir 'Programmability/StoredProcedures/stp_ExpireSessions.sql'
\ir 'Programmability/StoredProcedures/stp_InsertAuditLog.sql'
\ir 'Programmability/StoredProcedures/stp_MarkResetTokenUsed.sql'
\ir 'Programmability/StoredProcedures/stp_MarkSessionReplaced.sql'
\ir 'Programmability/StoredProcedures/stp_RemoveGroupMember.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeAllUserSessions.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeInvitation.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeSession.sql'
\ir 'Programmability/StoredProcedures/stp_RevokeTokenFamily.sql'
\ir 'Programmability/StoredProcedures/stp_SetGroupFeatures.sql'
\ir 'Programmability/StoredProcedures/stp_SetInvitationAcceptedBy.sql'
\ir 'Programmability/StoredProcedures/stp_SetUserActive.sql'
\ir 'Programmability/StoredProcedures/stp_SetUserPassword.sql'
\ir 'Programmability/StoredProcedures/stp_SoftDeleteUser.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateClient.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateGroup.sql'
\ir 'Programmability/StoredProcedures/stp_UpdateProduct.sql'
\ir 'Programmability/StoredProcedures/stp_UpsertProductPermission.sql'
