"""Regenerates db/build.sql from the filesystem, so adding an object file is
enough to include it in the build — no hand-maintained list to fall out of date.

Order is by LAYER (types -> tables -> views -> functions -> procedures); within a
layer, files are applied alphabetically for a stable diff.

Tables are the exception, and their order is LOAD-BEARING: each file adds its
foreign keys as soon as its table exists, so the referenced table -- and the
unique index a composite key targets -- must already be there. TABLE_ORDER lists
parents before children; a new table goes after everything it references.

Views are alphabetical, so a view that reads another view must sort after it.

Run:  python db/gen_build.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

TABLE_ORDER = [
    "tbl_clients", "tbl_scopes", "tbl_products", "tbl_product_roles", "tbl_product_redirect_uris",
    "tbl_sso_connections", "tbl_login_policies", "tbl_users", "tbl_platform_owners",
    "tbl_client_products", "tbl_groups", "tbl_session_families", "tbl_user_sessions",
    "tbl_product_permissions", "tbl_group_product_grants", "tbl_group_scopes", "tbl_user_scopes",
    "tbl_api_clients", "tbl_api_client_scopes", "tbl_api_client_products", "tbl_api_client_secrets",
    "tbl_user_groups", "tbl_group_managers", "tbl_linked_identities", "tbl_invitations", "tbl_invitation_groups",
    "tbl_audit_logs", "tbl_authorization_codes", "tbl_password_reset_tokens",
    "tbl_login_states", "tbl_sso_connection_domains", "tbl_rate_limit_counters",
]

def ls(rel):
    d = os.path.join(HERE, rel)
    return sorted(f for f in os.listdir(d) if f.endswith(".sql")) if os.path.isdir(d) else []

L = []
add = L.append
add("/****** Database build script ******/")
add("-- Applies every object in dependency order. Idempotent: safe to re-run, which")
add("-- is what makes it usable as both a fresh install and an upgrade.")
add("--")
add("--   psql -v ON_ERROR_STOP=1 -f db/build.sql")
add("--")
add("-- GENERATED by db/gen_build.py -- do not edit by hand.")
add("-- Order matters between layers, not within them:")
add("--   1. Extensions and Types  referenced by column definitions")
add("--   2. Tables                parents first: a foreign key needs its target")
add("--   3. Views                 read from tables")
add("--   4. Functions (udf_)      read from tables and views")
add("--   5. Procedures (stp_)     write to tables")
add("")
add(r"\set ON_ERROR_STOP on")
add("")
add("-- 0. Schema version guard " + "-" * 51)
add("-- This is the v3 baseline. It cannot upgrade an older database in place (a")
add("-- view cannot drop a column through CREATE OR REPLACE, and CREATE TABLE IF NOT")
add("-- EXISTS adds no column), so it refuses one outright rather than half-applying.")
add("-- See Migrations/README.md.")
add("DO $$")
add("BEGIN")
add("    IF EXISTS (SELECT 1 FROM information_schema.columns")
add("               WHERE table_name = 'tbl_users' AND column_name = 'is_global_admin') THEN")
add("        RAISE EXCEPTION 'v1 schema detected; rebuild the database from scratch (Migrations/README.md)';")
add("    END IF;")
add("    IF EXISTS (SELECT 1 FROM information_schema.tables")
add("               WHERE table_name = 'tbl_group_features') THEN")
add("        RAISE EXCEPTION 'v2 schema detected; rebuild the database from scratch (Migrations/README.md)';")
add("    END IF;")
add("END $$;")
add("")
add("-- 1. Extensions and types " + "-" * 51)
add("CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()")
add("")
# The type file uses plain CREATE TYPE so sqlc can parse it (a DO-block guard
# makes enums invisible to sqlc and degrades every enum to interface{}). That is
# not idempotent, so the guarded form is GENERATED here from that same file —
# one source of truth, no copy to drift.
import re as _re
_types = os.path.join(HERE, "Programmability", "Types", "enums.sql")
_stmts = _re.findall(r'CREATE TYPE\s+"(\w+)"\s+AS ENUM\s*\(([^)]*)\)', open(_types, encoding="utf-8").read())
add("-- Types: guarded form generated from Programmability/Types/enums.sql")
add("DO $$")
add("BEGIN")
for _name, _vals in _stmts:
    add(f"    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{_name}') THEN")
    add(f'        CREATE TYPE "{_name}" AS ENUM ({" ".join(_vals.split())});')
    add("    END IF;")
add("END $$;")

add("")
add("-- 2. Tables " + "-" * 65)
# Parents first for a readable fresh install, then everything else on disk. The
# remainder is discovered rather than listed, so adding a table file is enough to
# include it -- there is no hand-maintained list to fall out of date. Order is
# cosmetic anyway: the foreign keys inside each file are guarded.
_ordered = [t + ".sql" for t in TABLE_ORDER]
for t in _ordered:
    add(rf"\ir 'Tables/{t}'")
for t in ls("Tables"):
    if t not in _ordered:
        add(rf"\ir 'Tables/{t}'")

add("")
add("-- 3. Views " + "-" * 66)
for f in ls("Views"):
    add(rf"\ir 'Views/{f}'")

add("")
add("-- 4. Functions (reads) " + "-" * 54)
for f in ls("Programmability/Functions/Scalar-valued Functions"):
    add(rf"\ir 'Programmability/Functions/Scalar-valued Functions/{f}'")
add("")
for f in ls("Programmability/Functions/Table-valued Functions"):
    add(rf"\ir 'Programmability/Functions/Table-valued Functions/{f}'")

add("")
add("-- 5. Procedures (writes) " + "-" * 52)
for f in ls("Programmability/StoredProcedures"):
    add(rf"\ir 'Programmability/StoredProcedures/{f}'")
add("")

with open(os.path.join(HERE, "build.sql"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(L))
print(f"build.sql: {sum(1 for x in L if 'ir ' in x[:4])} object files referenced")
