"""Regenerates db/build.sql from the filesystem, so adding an object file is
enough to include it in the build — no hand-maintained list to fall out of date.

Order is by LAYER (types -> tables -> views -> functions -> procedures); within a
layer, files are independent and applied alphabetically for a stable diff.
Tables are the one exception: parents are listed first so a fresh install reads
cleanly, though the guarded foreign keys make the order technically irrelevant.

Run:  python db/gen_build.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

TABLE_ORDER = [
    "tbl_clients", "tbl_products", "tbl_users", "tbl_user_sessions",
    "tbl_client_products", "tbl_product_permissions", "tbl_linked_identities",
    "tbl_invitations", "tbl_invitation_products", "tbl_audit_logs",
    "tbl_authorization_codes", "tbl_groups", "tbl_group_features",
    "tbl_user_groups", "tbl_password_reset_tokens",
]

def ls(rel):
    d = os.path.join(HERE, rel)
    return sorted(f for f in os.listdir(d) if f.endswith(".sql")) if os.path.isdir(d) else []

L = []
add = L.append
add("/****** Database build script ******/")
add("-- Applies every object in dependency order. Idempotent: safe to re-run, which")
add("-- is what makes it usable as both a fresh install and an upgrade.")
add("--")
add("--   psql -v ON_ERROR_STOP=1 -f db/build.sql")
add("--")
add("-- GENERATED by db/gen_build.py -- do not edit by hand.")
add("-- Order matters between layers, not within them:")
add("--   1. Extensions and Types  referenced by column definitions")
add("--   2. Tables                foreign keys are guarded, so order is cosmetic")
add("--   3. Views                 read from tables")
add("--   4. Functions (udf_)      read from tables and views")
add("--   5. Procedures (stp_)     write to tables")
add("")
add("\set ON_ERROR_STOP on")
add("")
add("-- 1. Extensions and types " + "-" * 51)
add("CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()")
add("")
# The type file uses plain CREATE TYPE so sqlc can parse it (a DO-block guard
# makes enums invisible to sqlc and degrades every enum to interface{}). That is
# not idempotent, so the guarded form is GENERATED here from that same file —
# one source of truth, no copy to drift.
import re as _re
_types = os.path.join(HERE, "Programmability", "Types", "enums.sql")
_stmts = _re.findall(r'CREATE TYPE\s+"(\w+)"\s+AS ENUM\s*\(([^)]*)\)', open(_types, encoding="utf-8").read())
add("-- Types: guarded form generated from Programmability/Types/enums.sql")
add("DO $$")
add("BEGIN")
for _name, _vals in _stmts:
    add(f"    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{_name}') THEN")
    add(f'        CREATE TYPE "{_name}" AS ENUM ({" ".join(_vals.split())});')
    add("    END IF;")
add("END $$;")

add("")
add("-- 2. Tables " + "-" * 65)
# Parents first for a readable fresh install, then everything else on disk. The
# remainder is discovered rather than listed, so adding a table file is enough to
# include it -- there is no hand-maintained list to fall out of date. Order is
# cosmetic anyway: the foreign keys inside each file are guarded.
_ordered = [t + ".sql" for t in TABLE_ORDER]
for t in _ordered:
    add(f"\ir 'Tables/{t}'")
for t in ls("Tables"):
    if t not in _ordered:
        add(f"\ir 'Tables/{t}'")

add("")
add("-- 3. Views " + "-" * 66)
for f in ls("Views"):
    add(f"\ir 'Views/{f}'")

add("")
add("-- 4. Functions (reads) " + "-" * 54)
for f in ls("Programmability/Functions/Scalar-valued Functions"):
    add(f"\ir 'Programmability/Functions/Scalar-valued Functions/{f}'")
add("")
for f in ls("Programmability/Functions/Table-valued Functions"):
    add(f"\ir 'Programmability/Functions/Table-valued Functions/{f}'")

add("")
add("-- 5. Procedures (writes) " + "-" * 52)
for f in ls("Programmability/StoredProcedures"):
    add(f"\ir 'Programmability/StoredProcedures/{f}'")
add("")

with open(os.path.join(HERE, "build.sql"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(L))
print(f"build.sql: {sum(1 for x in L if 'ir ' in x[:4])} object files referenced")
